# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salamander_control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import salamander_joints_pb2 as salamander__joints__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='salamander_control.proto',
  package='salamander.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\x18salamander_control.proto\x12\x0fsalamander.msgs\x1a\x17salamander_joints.proto\"\xa5\x01\n\x11SalamanderControl\x12,\n\x04\x63mds\x18\x01 \x03(\x0b\x32\x1e.salamander.msgs.JointCommands\x12.\n\x07torques\x18\x02 \x03(\x0b\x32\x1d.salamander.msgs.JointTorques\x12\x32\n\x08\x61nalysis\x18\x03 \x01(\x0b\x32 .salamander.msgs.ControlAnalysis\"P\n\x0f\x43ontrolAnalysis\x12=\n\x12joints_consumption\x18\x01 \x03(\x0b\x32!.salamander.msgs.JointConsumption\"5\n\x10JointConsumption\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0b\x63onsumption\x18\x02 \x02(\x01\"L\n\rJointCommands\x12\x0c\n\x04name\x18\x01 \x02(\t\x12-\n\x08\x63ommands\x18\x02 \x03(\x0b\x32\x1b.salamander.msgs.JointState\"J\n\x0cJointTorques\x12\x0c\n\x04name\x18\x01 \x02(\t\x12,\n\x06torque\x18\x02 \x03(\x0b\x32\x1c.salamander.msgs.JointTorque')
  ,
  dependencies=[salamander__joints__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SALAMANDERCONTROL = _descriptor.Descriptor(
  name='SalamanderControl',
  full_name='salamander.msgs.SalamanderControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmds', full_name='salamander.msgs.SalamanderControl.cmds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='torques', full_name='salamander.msgs.SalamanderControl.torques', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='analysis', full_name='salamander.msgs.SalamanderControl.analysis', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=236,
)


_CONTROLANALYSIS = _descriptor.Descriptor(
  name='ControlAnalysis',
  full_name='salamander.msgs.ControlAnalysis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='joints_consumption', full_name='salamander.msgs.ControlAnalysis.joints_consumption', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=318,
)


_JOINTCONSUMPTION = _descriptor.Descriptor(
  name='JointConsumption',
  full_name='salamander.msgs.JointConsumption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='salamander.msgs.JointConsumption.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='consumption', full_name='salamander.msgs.JointConsumption.consumption', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=373,
)


_JOINTCOMMANDS = _descriptor.Descriptor(
  name='JointCommands',
  full_name='salamander.msgs.JointCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='salamander.msgs.JointCommands.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commands', full_name='salamander.msgs.JointCommands.commands', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=451,
)


_JOINTTORQUES = _descriptor.Descriptor(
  name='JointTorques',
  full_name='salamander.msgs.JointTorques',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='salamander.msgs.JointTorques.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='torque', full_name='salamander.msgs.JointTorques.torque', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=527,
)

_SALAMANDERCONTROL.fields_by_name['cmds'].message_type = _JOINTCOMMANDS
_SALAMANDERCONTROL.fields_by_name['torques'].message_type = _JOINTTORQUES
_SALAMANDERCONTROL.fields_by_name['analysis'].message_type = _CONTROLANALYSIS
_CONTROLANALYSIS.fields_by_name['joints_consumption'].message_type = _JOINTCONSUMPTION
_JOINTCOMMANDS.fields_by_name['commands'].message_type = salamander__joints__pb2._JOINTSTATE
_JOINTTORQUES.fields_by_name['torque'].message_type = salamander__joints__pb2._JOINTTORQUE
DESCRIPTOR.message_types_by_name['SalamanderControl'] = _SALAMANDERCONTROL
DESCRIPTOR.message_types_by_name['ControlAnalysis'] = _CONTROLANALYSIS
DESCRIPTOR.message_types_by_name['JointConsumption'] = _JOINTCONSUMPTION
DESCRIPTOR.message_types_by_name['JointCommands'] = _JOINTCOMMANDS
DESCRIPTOR.message_types_by_name['JointTorques'] = _JOINTTORQUES

SalamanderControl = _reflection.GeneratedProtocolMessageType('SalamanderControl', (_message.Message,), dict(
  DESCRIPTOR = _SALAMANDERCONTROL,
  __module__ = 'salamander_control_pb2'
  # @@protoc_insertion_point(class_scope:salamander.msgs.SalamanderControl)
  ))
_sym_db.RegisterMessage(SalamanderControl)

ControlAnalysis = _reflection.GeneratedProtocolMessageType('ControlAnalysis', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLANALYSIS,
  __module__ = 'salamander_control_pb2'
  # @@protoc_insertion_point(class_scope:salamander.msgs.ControlAnalysis)
  ))
_sym_db.RegisterMessage(ControlAnalysis)

JointConsumption = _reflection.GeneratedProtocolMessageType('JointConsumption', (_message.Message,), dict(
  DESCRIPTOR = _JOINTCONSUMPTION,
  __module__ = 'salamander_control_pb2'
  # @@protoc_insertion_point(class_scope:salamander.msgs.JointConsumption)
  ))
_sym_db.RegisterMessage(JointConsumption)

JointCommands = _reflection.GeneratedProtocolMessageType('JointCommands', (_message.Message,), dict(
  DESCRIPTOR = _JOINTCOMMANDS,
  __module__ = 'salamander_control_pb2'
  # @@protoc_insertion_point(class_scope:salamander.msgs.JointCommands)
  ))
_sym_db.RegisterMessage(JointCommands)

JointTorques = _reflection.GeneratedProtocolMessageType('JointTorques', (_message.Message,), dict(
  DESCRIPTOR = _JOINTTORQUES,
  __module__ = 'salamander_control_pb2'
  # @@protoc_insertion_point(class_scope:salamander.msgs.JointTorques)
  ))
_sym_db.RegisterMessage(JointTorques)


# @@protoc_insertion_point(module_scope)
