# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salamander_joints.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import time_pb2 as time__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='salamander_joints.proto',
  package='salamander.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\x17salamander_joints.proto\x12\x0fsalamander.msgs\x1a\ntime.proto\"K\n\x0fJointKinematics\x12\x0c\n\x04name\x18\x01 \x02(\t\x12*\n\x05state\x18\x02 \x03(\x0b\x32\x1b.salamander.msgs.JointState\"Q\n\nJointState\x12\x1f\n\x04time\x18\x01 \x02(\x0b\x32\x11.gazebo.msgs.Time\x12\x10\n\x08position\x18\x02 \x02(\x01\x12\x10\n\x08velocity\x18\x03 \x01(\x01\".\n\x08JointCmd\x12\x10\n\x08position\x18\x01 \x02(\x01\x12\x10\n\x08velocity\x18\x02 \x01(\x01')
  ,
  dependencies=[time__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_JOINTKINEMATICS = _descriptor.Descriptor(
  name='JointKinematics',
  full_name='salamander.msgs.JointKinematics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='salamander.msgs.JointKinematics.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='salamander.msgs.JointKinematics.state', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=131,
)


_JOINTSTATE = _descriptor.Descriptor(
  name='JointState',
  full_name='salamander.msgs.JointState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='salamander.msgs.JointState.time', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='salamander.msgs.JointState.position', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='salamander.msgs.JointState.velocity', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=214,
)


_JOINTCMD = _descriptor.Descriptor(
  name='JointCmd',
  full_name='salamander.msgs.JointCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='salamander.msgs.JointCmd.position', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='salamander.msgs.JointCmd.velocity', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=262,
)

_JOINTKINEMATICS.fields_by_name['state'].message_type = _JOINTSTATE
_JOINTSTATE.fields_by_name['time'].message_type = time__pb2._TIME
DESCRIPTOR.message_types_by_name['JointKinematics'] = _JOINTKINEMATICS
DESCRIPTOR.message_types_by_name['JointState'] = _JOINTSTATE
DESCRIPTOR.message_types_by_name['JointCmd'] = _JOINTCMD

JointKinematics = _reflection.GeneratedProtocolMessageType('JointKinematics', (_message.Message,), dict(
  DESCRIPTOR = _JOINTKINEMATICS,
  __module__ = 'salamander_joints_pb2'
  # @@protoc_insertion_point(class_scope:salamander.msgs.JointKinematics)
  ))
_sym_db.RegisterMessage(JointKinematics)

JointState = _reflection.GeneratedProtocolMessageType('JointState', (_message.Message,), dict(
  DESCRIPTOR = _JOINTSTATE,
  __module__ = 'salamander_joints_pb2'
  # @@protoc_insertion_point(class_scope:salamander.msgs.JointState)
  ))
_sym_db.RegisterMessage(JointState)

JointCmd = _reflection.GeneratedProtocolMessageType('JointCmd', (_message.Message,), dict(
  DESCRIPTOR = _JOINTCMD,
  __module__ = 'salamander_joints_pb2'
  # @@protoc_insertion_point(class_scope:salamander.msgs.JointCmd)
  ))
_sym_db.RegisterMessage(JointCmd)


# @@protoc_insertion_point(module_scope)
