# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salamander_kinematics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import salamander_links_pb2 as salamander__links__pb2
from . import salamander_joints_pb2 as salamander__joints__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='salamander_kinematics.proto',
  package='salamander.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\x1bsalamander_kinematics.proto\x12\x0fsalamander.msgs\x1a\x16salamander_links.proto\x1a\x17salamander_joints.proto\"s\n\x0fModelKinematics\x12.\n\x05links\x18\x01 \x03(\x0b\x32\x1f.salamander.msgs.LinkKinematics\x12\x30\n\x06joints\x18\x02 \x03(\x0b\x32 .salamander.msgs.JointKinematics')
  ,
  dependencies=[salamander__links__pb2.DESCRIPTOR,salamander__joints__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODELKINEMATICS = _descriptor.Descriptor(
  name='ModelKinematics',
  full_name='salamander.msgs.ModelKinematics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='links', full_name='salamander.msgs.ModelKinematics.links', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='joints', full_name='salamander.msgs.ModelKinematics.joints', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=212,
)

_MODELKINEMATICS.fields_by_name['links'].message_type = salamander__links__pb2._LINKKINEMATICS
_MODELKINEMATICS.fields_by_name['joints'].message_type = salamander__joints__pb2._JOINTKINEMATICS
DESCRIPTOR.message_types_by_name['ModelKinematics'] = _MODELKINEMATICS

ModelKinematics = _reflection.GeneratedProtocolMessageType('ModelKinematics', (_message.Message,), dict(
  DESCRIPTOR = _MODELKINEMATICS,
  __module__ = 'salamander_kinematics_pb2'
  # @@protoc_insertion_point(class_scope:salamander.msgs.ModelKinematics)
  ))
_sym_db.RegisterMessage(ModelKinematics)


# @@protoc_insertion_point(module_scope)
