# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salamander_control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import time_pb2 as time__pb2
from . import salamander_joints_pb2 as salamander__joints__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='salamander_control.proto',
  package='salamander.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\x18salamander_control.proto\x12\x0fsalamander.msgs\x1a\ntime.proto\x1a\x17salamander_joints.proto\"B\n\x11SalamanderControl\x12-\n\x06joints\x18\x01 \x03(\x0b\x32\x1d.salamander.msgs.JointControl\"M\n\x0cJointControl\x12\x0c\n\x04name\x18\x01 \x02(\t\x12/\n\x07\x63ontrol\x18\x02 \x03(\x0b\x32\x1e.salamander.msgs.JointCommands\"\x82\x01\n\rJointCommands\x12\x1f\n\x04time\x18\x01 \x02(\x0b\x32\x11.gazebo.msgs.Time\x12+\n\x08\x63ommands\x18\x02 \x02(\x0b\x32\x19.salamander.msgs.JointCmd\x12\x0e\n\x06torque\x18\x03 \x02(\x01\x12\x13\n\x0b\x63onsumption\x18\x04 \x01(\x01')
  ,
  dependencies=[time__pb2.DESCRIPTOR,salamander__joints__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SALAMANDERCONTROL = _descriptor.Descriptor(
  name='SalamanderControl',
  full_name='salamander.msgs.SalamanderControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='joints', full_name='salamander.msgs.SalamanderControl.joints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=148,
)


_JOINTCONTROL = _descriptor.Descriptor(
  name='JointControl',
  full_name='salamander.msgs.JointControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='salamander.msgs.JointControl.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='control', full_name='salamander.msgs.JointControl.control', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=227,
)


_JOINTCOMMANDS = _descriptor.Descriptor(
  name='JointCommands',
  full_name='salamander.msgs.JointCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='salamander.msgs.JointCommands.time', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commands', full_name='salamander.msgs.JointCommands.commands', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='torque', full_name='salamander.msgs.JointCommands.torque', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='consumption', full_name='salamander.msgs.JointCommands.consumption', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=360,
)

_SALAMANDERCONTROL.fields_by_name['joints'].message_type = _JOINTCONTROL
_JOINTCONTROL.fields_by_name['control'].message_type = _JOINTCOMMANDS
_JOINTCOMMANDS.fields_by_name['time'].message_type = time__pb2._TIME
_JOINTCOMMANDS.fields_by_name['commands'].message_type = salamander__joints__pb2._JOINTCMD
DESCRIPTOR.message_types_by_name['SalamanderControl'] = _SALAMANDERCONTROL
DESCRIPTOR.message_types_by_name['JointControl'] = _JOINTCONTROL
DESCRIPTOR.message_types_by_name['JointCommands'] = _JOINTCOMMANDS

SalamanderControl = _reflection.GeneratedProtocolMessageType('SalamanderControl', (_message.Message,), dict(
  DESCRIPTOR = _SALAMANDERCONTROL,
  __module__ = 'salamander_control_pb2'
  # @@protoc_insertion_point(class_scope:salamander.msgs.SalamanderControl)
  ))
_sym_db.RegisterMessage(SalamanderControl)

JointControl = _reflection.GeneratedProtocolMessageType('JointControl', (_message.Message,), dict(
  DESCRIPTOR = _JOINTCONTROL,
  __module__ = 'salamander_control_pb2'
  # @@protoc_insertion_point(class_scope:salamander.msgs.JointControl)
  ))
_sym_db.RegisterMessage(JointControl)

JointCommands = _reflection.GeneratedProtocolMessageType('JointCommands', (_message.Message,), dict(
  DESCRIPTOR = _JOINTCOMMANDS,
  __module__ = 'salamander_control_pb2'
  # @@protoc_insertion_point(class_scope:salamander.msgs.JointCommands)
  ))
_sym_db.RegisterMessage(JointCommands)


# @@protoc_insertion_point(module_scope)
