// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_kinematics.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "log_kinematics.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace salamander {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* ModelKinematics_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ModelKinematics_reflection_ = NULL;
const ::google::protobuf::Descriptor* LinkKinematics_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LinkKinematics_reflection_ = NULL;
const ::google::protobuf::Descriptor* LinkState_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LinkState_reflection_ = NULL;
const ::google::protobuf::Descriptor* JointsKinematics_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  JointsKinematics_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_log_5fkinematics_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_log_5fkinematics_2eproto() {
  protobuf_AddDesc_log_5fkinematics_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "log_kinematics.proto");
  GOOGLE_CHECK(file != NULL);
  ModelKinematics_descriptor_ = file->message_type(0);
  static const int ModelKinematics_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelKinematics, links_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelKinematics, joints_),
  };
  ModelKinematics_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ModelKinematics_descriptor_,
      ModelKinematics::default_instance_,
      ModelKinematics_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelKinematics, _has_bits_[0]),
      -1,
      -1,
      sizeof(ModelKinematics),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelKinematics, _internal_metadata_),
      -1);
  LinkKinematics_descriptor_ = file->message_type(1);
  static const int LinkKinematics_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkKinematics, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkKinematics, state_),
  };
  LinkKinematics_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LinkKinematics_descriptor_,
      LinkKinematics::default_instance_,
      LinkKinematics_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkKinematics, _has_bits_[0]),
      -1,
      -1,
      sizeof(LinkKinematics),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkKinematics, _internal_metadata_),
      -1);
  LinkState_descriptor_ = file->message_type(2);
  static const int LinkState_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkState, time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkState, pose_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkState, linear_velocity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkState, angular_velocity_),
  };
  LinkState_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LinkState_descriptor_,
      LinkState::default_instance_,
      LinkState_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkState, _has_bits_[0]),
      -1,
      -1,
      sizeof(LinkState),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LinkState, _internal_metadata_),
      -1);
  JointsKinematics_descriptor_ = file->message_type(3);
  static const int JointsKinematics_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointsKinematics, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointsKinematics, joint_),
  };
  JointsKinematics_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      JointsKinematics_descriptor_,
      JointsKinematics::default_instance_,
      JointsKinematics_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointsKinematics, _has_bits_[0]),
      -1,
      -1,
      sizeof(JointsKinematics),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointsKinematics, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_log_5fkinematics_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ModelKinematics_descriptor_, &ModelKinematics::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LinkKinematics_descriptor_, &LinkKinematics::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LinkState_descriptor_, &LinkState::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      JointsKinematics_descriptor_, &JointsKinematics::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_log_5fkinematics_2eproto() {
  delete ModelKinematics::default_instance_;
  delete ModelKinematics_reflection_;
  delete LinkKinematics::default_instance_;
  delete LinkKinematics_reflection_;
  delete LinkState::default_instance_;
  delete LinkState_reflection_;
  delete JointsKinematics::default_instance_;
  delete JointsKinematics_reflection_;
}

void protobuf_AddDesc_log_5fkinematics_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_log_5fkinematics_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::gazebo::msgs::protobuf_AddDesc_time_2eproto();
  ::gazebo::msgs::protobuf_AddDesc_pose_2eproto();
  ::gazebo::msgs::protobuf_AddDesc_joint_2eproto();
  ::gazebo::msgs::protobuf_AddDesc_vector3d_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024log_kinematics.proto\022\017salamander.msgs\032"
    "\ntime.proto\032\npose.proto\032\013joint.proto\032\016ve"
    "ctor3d.proto\"t\n\017ModelKinematics\022.\n\005links"
    "\030\001 \003(\0132\037.salamander.msgs.LinkKinematics\022"
    "1\n\006joints\030\002 \003(\0132!.salamander.msgs.Joints"
    "Kinematics\"I\n\016LinkKinematics\022\014\n\004name\030\001 \002"
    "(\t\022)\n\005state\030\002 \003(\0132\032.salamander.msgs.Link"
    "State\"\256\001\n\tLinkState\022\037\n\004time\030\001 \002(\0132\021.gaze"
    "bo.msgs.Time\022\037\n\004pose\030\002 \002(\0132\021.gazebo.msgs"
    ".Pose\022.\n\017linear_velocity\030\003 \001(\0132\025.gazebo."
    "msgs.Vector3d\022/\n\020angular_velocity\030\004 \001(\0132"
    "\025.gazebo.msgs.Vector3d\"C\n\020JointsKinemati"
    "cs\022\014\n\004name\030\001 \002(\t\022!\n\005joint\030\002 \003(\0132\022.gazebo"
    ".msgs.Joint", 531);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "log_kinematics.proto", &protobuf_RegisterTypes);
  ModelKinematics::default_instance_ = new ModelKinematics();
  LinkKinematics::default_instance_ = new LinkKinematics();
  LinkState::default_instance_ = new LinkState();
  JointsKinematics::default_instance_ = new JointsKinematics();
  ModelKinematics::default_instance_->InitAsDefaultInstance();
  LinkKinematics::default_instance_->InitAsDefaultInstance();
  LinkState::default_instance_->InitAsDefaultInstance();
  JointsKinematics::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_log_5fkinematics_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_log_5fkinematics_2eproto {
  StaticDescriptorInitializer_log_5fkinematics_2eproto() {
    protobuf_AddDesc_log_5fkinematics_2eproto();
  }
} static_descriptor_initializer_log_5fkinematics_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ModelKinematics::kLinksFieldNumber;
const int ModelKinematics::kJointsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ModelKinematics::ModelKinematics()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:salamander.msgs.ModelKinematics)
}

void ModelKinematics::InitAsDefaultInstance() {
}

ModelKinematics::ModelKinematics(const ModelKinematics& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:salamander.msgs.ModelKinematics)
}

void ModelKinematics::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ModelKinematics::~ModelKinematics() {
  // @@protoc_insertion_point(destructor:salamander.msgs.ModelKinematics)
  SharedDtor();
}

void ModelKinematics::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ModelKinematics::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ModelKinematics::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ModelKinematics_descriptor_;
}

const ModelKinematics& ModelKinematics::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_log_5fkinematics_2eproto();
  return *default_instance_;
}

ModelKinematics* ModelKinematics::default_instance_ = NULL;

ModelKinematics* ModelKinematics::New(::google::protobuf::Arena* arena) const {
  ModelKinematics* n = new ModelKinematics;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ModelKinematics::Clear() {
// @@protoc_insertion_point(message_clear_start:salamander.msgs.ModelKinematics)
  links_.Clear();
  joints_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool ModelKinematics::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:salamander.msgs.ModelKinematics)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .salamander.msgs.LinkKinematics links = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_links:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_links()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_links;
        if (input->ExpectTag(18)) goto parse_loop_joints;
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .salamander.msgs.JointsKinematics joints = 2;
      case 2: {
        if (tag == 18) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_joints:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_joints()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_joints;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:salamander.msgs.ModelKinematics)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:salamander.msgs.ModelKinematics)
  return false;
#undef DO_
}

void ModelKinematics::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:salamander.msgs.ModelKinematics)
  // repeated .salamander.msgs.LinkKinematics links = 1;
  for (unsigned int i = 0, n = this->links_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->links(i), output);
  }

  // repeated .salamander.msgs.JointsKinematics joints = 2;
  for (unsigned int i = 0, n = this->joints_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->joints(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:salamander.msgs.ModelKinematics)
}

::google::protobuf::uint8* ModelKinematics::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:salamander.msgs.ModelKinematics)
  // repeated .salamander.msgs.LinkKinematics links = 1;
  for (unsigned int i = 0, n = this->links_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->links(i), false, target);
  }

  // repeated .salamander.msgs.JointsKinematics joints = 2;
  for (unsigned int i = 0, n = this->joints_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->joints(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:salamander.msgs.ModelKinematics)
  return target;
}

int ModelKinematics::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:salamander.msgs.ModelKinematics)
  int total_size = 0;

  // repeated .salamander.msgs.LinkKinematics links = 1;
  total_size += 1 * this->links_size();
  for (int i = 0; i < this->links_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->links(i));
  }

  // repeated .salamander.msgs.JointsKinematics joints = 2;
  total_size += 1 * this->joints_size();
  for (int i = 0; i < this->joints_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->joints(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ModelKinematics::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:salamander.msgs.ModelKinematics)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ModelKinematics* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ModelKinematics>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:salamander.msgs.ModelKinematics)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:salamander.msgs.ModelKinematics)
    MergeFrom(*source);
  }
}

void ModelKinematics::MergeFrom(const ModelKinematics& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:salamander.msgs.ModelKinematics)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  links_.MergeFrom(from.links_);
  joints_.MergeFrom(from.joints_);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void ModelKinematics::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:salamander.msgs.ModelKinematics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ModelKinematics::CopyFrom(const ModelKinematics& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:salamander.msgs.ModelKinematics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ModelKinematics::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->links())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->joints())) return false;
  return true;
}

void ModelKinematics::Swap(ModelKinematics* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ModelKinematics::InternalSwap(ModelKinematics* other) {
  links_.UnsafeArenaSwap(&other->links_);
  joints_.UnsafeArenaSwap(&other->joints_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ModelKinematics::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ModelKinematics_descriptor_;
  metadata.reflection = ModelKinematics_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ModelKinematics

// repeated .salamander.msgs.LinkKinematics links = 1;
int ModelKinematics::links_size() const {
  return links_.size();
}
void ModelKinematics::clear_links() {
  links_.Clear();
}
const ::salamander::msgs::LinkKinematics& ModelKinematics::links(int index) const {
  // @@protoc_insertion_point(field_get:salamander.msgs.ModelKinematics.links)
  return links_.Get(index);
}
::salamander::msgs::LinkKinematics* ModelKinematics::mutable_links(int index) {
  // @@protoc_insertion_point(field_mutable:salamander.msgs.ModelKinematics.links)
  return links_.Mutable(index);
}
::salamander::msgs::LinkKinematics* ModelKinematics::add_links() {
  // @@protoc_insertion_point(field_add:salamander.msgs.ModelKinematics.links)
  return links_.Add();
}
::google::protobuf::RepeatedPtrField< ::salamander::msgs::LinkKinematics >*
ModelKinematics::mutable_links() {
  // @@protoc_insertion_point(field_mutable_list:salamander.msgs.ModelKinematics.links)
  return &links_;
}
const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::LinkKinematics >&
ModelKinematics::links() const {
  // @@protoc_insertion_point(field_list:salamander.msgs.ModelKinematics.links)
  return links_;
}

// repeated .salamander.msgs.JointsKinematics joints = 2;
int ModelKinematics::joints_size() const {
  return joints_.size();
}
void ModelKinematics::clear_joints() {
  joints_.Clear();
}
const ::salamander::msgs::JointsKinematics& ModelKinematics::joints(int index) const {
  // @@protoc_insertion_point(field_get:salamander.msgs.ModelKinematics.joints)
  return joints_.Get(index);
}
::salamander::msgs::JointsKinematics* ModelKinematics::mutable_joints(int index) {
  // @@protoc_insertion_point(field_mutable:salamander.msgs.ModelKinematics.joints)
  return joints_.Mutable(index);
}
::salamander::msgs::JointsKinematics* ModelKinematics::add_joints() {
  // @@protoc_insertion_point(field_add:salamander.msgs.ModelKinematics.joints)
  return joints_.Add();
}
::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointsKinematics >*
ModelKinematics::mutable_joints() {
  // @@protoc_insertion_point(field_mutable_list:salamander.msgs.ModelKinematics.joints)
  return &joints_;
}
const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointsKinematics >&
ModelKinematics::joints() const {
  // @@protoc_insertion_point(field_list:salamander.msgs.ModelKinematics.joints)
  return joints_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LinkKinematics::kNameFieldNumber;
const int LinkKinematics::kStateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LinkKinematics::LinkKinematics()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:salamander.msgs.LinkKinematics)
}

void LinkKinematics::InitAsDefaultInstance() {
}

LinkKinematics::LinkKinematics(const LinkKinematics& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:salamander.msgs.LinkKinematics)
}

void LinkKinematics::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LinkKinematics::~LinkKinematics() {
  // @@protoc_insertion_point(destructor:salamander.msgs.LinkKinematics)
  SharedDtor();
}

void LinkKinematics::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void LinkKinematics::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LinkKinematics::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LinkKinematics_descriptor_;
}

const LinkKinematics& LinkKinematics::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_log_5fkinematics_2eproto();
  return *default_instance_;
}

LinkKinematics* LinkKinematics::default_instance_ = NULL;

LinkKinematics* LinkKinematics::New(::google::protobuf::Arena* arena) const {
  LinkKinematics* n = new LinkKinematics;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LinkKinematics::Clear() {
// @@protoc_insertion_point(message_clear_start:salamander.msgs.LinkKinematics)
  if (has_name()) {
    name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  state_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool LinkKinematics::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:salamander.msgs.LinkKinematics)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "salamander.msgs.LinkKinematics.name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_state;
        break;
      }

      // repeated .salamander.msgs.LinkState state = 2;
      case 2: {
        if (tag == 18) {
         parse_state:
          DO_(input->IncrementRecursionDepth());
         parse_loop_state:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_state()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_state;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:salamander.msgs.LinkKinematics)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:salamander.msgs.LinkKinematics)
  return false;
#undef DO_
}

void LinkKinematics::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:salamander.msgs.LinkKinematics)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "salamander.msgs.LinkKinematics.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // repeated .salamander.msgs.LinkState state = 2;
  for (unsigned int i = 0, n = this->state_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->state(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:salamander.msgs.LinkKinematics)
}

::google::protobuf::uint8* LinkKinematics::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:salamander.msgs.LinkKinematics)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "salamander.msgs.LinkKinematics.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // repeated .salamander.msgs.LinkState state = 2;
  for (unsigned int i = 0, n = this->state_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->state(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:salamander.msgs.LinkKinematics)
  return target;
}

int LinkKinematics::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:salamander.msgs.LinkKinematics)
  int total_size = 0;

  // required string name = 1;
  if (has_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }
  // repeated .salamander.msgs.LinkState state = 2;
  total_size += 1 * this->state_size();
  for (int i = 0; i < this->state_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->state(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LinkKinematics::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:salamander.msgs.LinkKinematics)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const LinkKinematics* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const LinkKinematics>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:salamander.msgs.LinkKinematics)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:salamander.msgs.LinkKinematics)
    MergeFrom(*source);
  }
}

void LinkKinematics::MergeFrom(const LinkKinematics& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:salamander.msgs.LinkKinematics)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  state_.MergeFrom(from.state_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void LinkKinematics::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:salamander.msgs.LinkKinematics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LinkKinematics::CopyFrom(const LinkKinematics& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:salamander.msgs.LinkKinematics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LinkKinematics::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->state())) return false;
  return true;
}

void LinkKinematics::Swap(LinkKinematics* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LinkKinematics::InternalSwap(LinkKinematics* other) {
  name_.Swap(&other->name_);
  state_.UnsafeArenaSwap(&other->state_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LinkKinematics::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LinkKinematics_descriptor_;
  metadata.reflection = LinkKinematics_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LinkKinematics

// required string name = 1;
bool LinkKinematics::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void LinkKinematics::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
void LinkKinematics::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void LinkKinematics::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
 const ::std::string& LinkKinematics::name() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.LinkKinematics.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LinkKinematics::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:salamander.msgs.LinkKinematics.name)
}
 void LinkKinematics::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:salamander.msgs.LinkKinematics.name)
}
 void LinkKinematics::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:salamander.msgs.LinkKinematics.name)
}
 ::std::string* LinkKinematics::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:salamander.msgs.LinkKinematics.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* LinkKinematics::release_name() {
  // @@protoc_insertion_point(field_release:salamander.msgs.LinkKinematics.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LinkKinematics::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.LinkKinematics.name)
}

// repeated .salamander.msgs.LinkState state = 2;
int LinkKinematics::state_size() const {
  return state_.size();
}
void LinkKinematics::clear_state() {
  state_.Clear();
}
const ::salamander::msgs::LinkState& LinkKinematics::state(int index) const {
  // @@protoc_insertion_point(field_get:salamander.msgs.LinkKinematics.state)
  return state_.Get(index);
}
::salamander::msgs::LinkState* LinkKinematics::mutable_state(int index) {
  // @@protoc_insertion_point(field_mutable:salamander.msgs.LinkKinematics.state)
  return state_.Mutable(index);
}
::salamander::msgs::LinkState* LinkKinematics::add_state() {
  // @@protoc_insertion_point(field_add:salamander.msgs.LinkKinematics.state)
  return state_.Add();
}
::google::protobuf::RepeatedPtrField< ::salamander::msgs::LinkState >*
LinkKinematics::mutable_state() {
  // @@protoc_insertion_point(field_mutable_list:salamander.msgs.LinkKinematics.state)
  return &state_;
}
const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::LinkState >&
LinkKinematics::state() const {
  // @@protoc_insertion_point(field_list:salamander.msgs.LinkKinematics.state)
  return state_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LinkState::kTimeFieldNumber;
const int LinkState::kPoseFieldNumber;
const int LinkState::kLinearVelocityFieldNumber;
const int LinkState::kAngularVelocityFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LinkState::LinkState()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:salamander.msgs.LinkState)
}

void LinkState::InitAsDefaultInstance() {
  time_ = const_cast< ::gazebo::msgs::Time*>(&::gazebo::msgs::Time::default_instance());
  pose_ = const_cast< ::gazebo::msgs::Pose*>(&::gazebo::msgs::Pose::default_instance());
  linear_velocity_ = const_cast< ::gazebo::msgs::Vector3d*>(&::gazebo::msgs::Vector3d::default_instance());
  angular_velocity_ = const_cast< ::gazebo::msgs::Vector3d*>(&::gazebo::msgs::Vector3d::default_instance());
}

LinkState::LinkState(const LinkState& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:salamander.msgs.LinkState)
}

void LinkState::SharedCtor() {
  _cached_size_ = 0;
  time_ = NULL;
  pose_ = NULL;
  linear_velocity_ = NULL;
  angular_velocity_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LinkState::~LinkState() {
  // @@protoc_insertion_point(destructor:salamander.msgs.LinkState)
  SharedDtor();
}

void LinkState::SharedDtor() {
  if (this != default_instance_) {
    delete time_;
    delete pose_;
    delete linear_velocity_;
    delete angular_velocity_;
  }
}

void LinkState::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LinkState::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LinkState_descriptor_;
}

const LinkState& LinkState::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_log_5fkinematics_2eproto();
  return *default_instance_;
}

LinkState* LinkState::default_instance_ = NULL;

LinkState* LinkState::New(::google::protobuf::Arena* arena) const {
  LinkState* n = new LinkState;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LinkState::Clear() {
// @@protoc_insertion_point(message_clear_start:salamander.msgs.LinkState)
  if (_has_bits_[0 / 32] & 15u) {
    if (has_time()) {
      if (time_ != NULL) time_->::gazebo::msgs::Time::Clear();
    }
    if (has_pose()) {
      if (pose_ != NULL) pose_->::gazebo::msgs::Pose::Clear();
    }
    if (has_linear_velocity()) {
      if (linear_velocity_ != NULL) linear_velocity_->::gazebo::msgs::Vector3d::Clear();
    }
    if (has_angular_velocity()) {
      if (angular_velocity_ != NULL) angular_velocity_->::gazebo::msgs::Vector3d::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool LinkState::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:salamander.msgs.LinkState)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .gazebo.msgs.Time time = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_time()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_pose;
        break;
      }

      // required .gazebo.msgs.Pose pose = 2;
      case 2: {
        if (tag == 18) {
         parse_pose:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_pose()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_linear_velocity;
        break;
      }

      // optional .gazebo.msgs.Vector3d linear_velocity = 3;
      case 3: {
        if (tag == 26) {
         parse_linear_velocity:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_linear_velocity()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_angular_velocity;
        break;
      }

      // optional .gazebo.msgs.Vector3d angular_velocity = 4;
      case 4: {
        if (tag == 34) {
         parse_angular_velocity:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_angular_velocity()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:salamander.msgs.LinkState)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:salamander.msgs.LinkState)
  return false;
#undef DO_
}

void LinkState::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:salamander.msgs.LinkState)
  // required .gazebo.msgs.Time time = 1;
  if (has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->time_, output);
  }

  // required .gazebo.msgs.Pose pose = 2;
  if (has_pose()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->pose_, output);
  }

  // optional .gazebo.msgs.Vector3d linear_velocity = 3;
  if (has_linear_velocity()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->linear_velocity_, output);
  }

  // optional .gazebo.msgs.Vector3d angular_velocity = 4;
  if (has_angular_velocity()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->angular_velocity_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:salamander.msgs.LinkState)
}

::google::protobuf::uint8* LinkState::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:salamander.msgs.LinkState)
  // required .gazebo.msgs.Time time = 1;
  if (has_time()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->time_, false, target);
  }

  // required .gazebo.msgs.Pose pose = 2;
  if (has_pose()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->pose_, false, target);
  }

  // optional .gazebo.msgs.Vector3d linear_velocity = 3;
  if (has_linear_velocity()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->linear_velocity_, false, target);
  }

  // optional .gazebo.msgs.Vector3d angular_velocity = 4;
  if (has_angular_velocity()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->angular_velocity_, false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:salamander.msgs.LinkState)
  return target;
}

int LinkState::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:salamander.msgs.LinkState)
  int total_size = 0;

  if (has_time()) {
    // required .gazebo.msgs.Time time = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->time_);
  }

  if (has_pose()) {
    // required .gazebo.msgs.Pose pose = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->pose_);
  }

  return total_size;
}
int LinkState::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:salamander.msgs.LinkState)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required .gazebo.msgs.Time time = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->time_);

    // required .gazebo.msgs.Pose pose = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->pose_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_has_bits_[2 / 32] & 12u) {
    // optional .gazebo.msgs.Vector3d linear_velocity = 3;
    if (has_linear_velocity()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->linear_velocity_);
    }

    // optional .gazebo.msgs.Vector3d angular_velocity = 4;
    if (has_angular_velocity()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->angular_velocity_);
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LinkState::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:salamander.msgs.LinkState)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const LinkState* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const LinkState>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:salamander.msgs.LinkState)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:salamander.msgs.LinkState)
    MergeFrom(*source);
  }
}

void LinkState::MergeFrom(const LinkState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:salamander.msgs.LinkState)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_time()) {
      mutable_time()->::gazebo::msgs::Time::MergeFrom(from.time());
    }
    if (from.has_pose()) {
      mutable_pose()->::gazebo::msgs::Pose::MergeFrom(from.pose());
    }
    if (from.has_linear_velocity()) {
      mutable_linear_velocity()->::gazebo::msgs::Vector3d::MergeFrom(from.linear_velocity());
    }
    if (from.has_angular_velocity()) {
      mutable_angular_velocity()->::gazebo::msgs::Vector3d::MergeFrom(from.angular_velocity());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void LinkState::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:salamander.msgs.LinkState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LinkState::CopyFrom(const LinkState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:salamander.msgs.LinkState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LinkState::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_time()) {
    if (!this->time_->IsInitialized()) return false;
  }
  if (has_pose()) {
    if (!this->pose_->IsInitialized()) return false;
  }
  if (has_linear_velocity()) {
    if (!this->linear_velocity_->IsInitialized()) return false;
  }
  if (has_angular_velocity()) {
    if (!this->angular_velocity_->IsInitialized()) return false;
  }
  return true;
}

void LinkState::Swap(LinkState* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LinkState::InternalSwap(LinkState* other) {
  std::swap(time_, other->time_);
  std::swap(pose_, other->pose_);
  std::swap(linear_velocity_, other->linear_velocity_);
  std::swap(angular_velocity_, other->angular_velocity_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LinkState::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LinkState_descriptor_;
  metadata.reflection = LinkState_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LinkState

// required .gazebo.msgs.Time time = 1;
bool LinkState::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void LinkState::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
void LinkState::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
void LinkState::clear_time() {
  if (time_ != NULL) time_->::gazebo::msgs::Time::Clear();
  clear_has_time();
}
const ::gazebo::msgs::Time& LinkState::time() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.LinkState.time)
  return time_ != NULL ? *time_ : *default_instance_->time_;
}
::gazebo::msgs::Time* LinkState::mutable_time() {
  set_has_time();
  if (time_ == NULL) {
    time_ = new ::gazebo::msgs::Time;
  }
  // @@protoc_insertion_point(field_mutable:salamander.msgs.LinkState.time)
  return time_;
}
::gazebo::msgs::Time* LinkState::release_time() {
  // @@protoc_insertion_point(field_release:salamander.msgs.LinkState.time)
  clear_has_time();
  ::gazebo::msgs::Time* temp = time_;
  time_ = NULL;
  return temp;
}
void LinkState::set_allocated_time(::gazebo::msgs::Time* time) {
  delete time_;
  time_ = time;
  if (time) {
    set_has_time();
  } else {
    clear_has_time();
  }
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.LinkState.time)
}

// required .gazebo.msgs.Pose pose = 2;
bool LinkState::has_pose() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void LinkState::set_has_pose() {
  _has_bits_[0] |= 0x00000002u;
}
void LinkState::clear_has_pose() {
  _has_bits_[0] &= ~0x00000002u;
}
void LinkState::clear_pose() {
  if (pose_ != NULL) pose_->::gazebo::msgs::Pose::Clear();
  clear_has_pose();
}
const ::gazebo::msgs::Pose& LinkState::pose() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.LinkState.pose)
  return pose_ != NULL ? *pose_ : *default_instance_->pose_;
}
::gazebo::msgs::Pose* LinkState::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) {
    pose_ = new ::gazebo::msgs::Pose;
  }
  // @@protoc_insertion_point(field_mutable:salamander.msgs.LinkState.pose)
  return pose_;
}
::gazebo::msgs::Pose* LinkState::release_pose() {
  // @@protoc_insertion_point(field_release:salamander.msgs.LinkState.pose)
  clear_has_pose();
  ::gazebo::msgs::Pose* temp = pose_;
  pose_ = NULL;
  return temp;
}
void LinkState::set_allocated_pose(::gazebo::msgs::Pose* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.LinkState.pose)
}

// optional .gazebo.msgs.Vector3d linear_velocity = 3;
bool LinkState::has_linear_velocity() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void LinkState::set_has_linear_velocity() {
  _has_bits_[0] |= 0x00000004u;
}
void LinkState::clear_has_linear_velocity() {
  _has_bits_[0] &= ~0x00000004u;
}
void LinkState::clear_linear_velocity() {
  if (linear_velocity_ != NULL) linear_velocity_->::gazebo::msgs::Vector3d::Clear();
  clear_has_linear_velocity();
}
const ::gazebo::msgs::Vector3d& LinkState::linear_velocity() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.LinkState.linear_velocity)
  return linear_velocity_ != NULL ? *linear_velocity_ : *default_instance_->linear_velocity_;
}
::gazebo::msgs::Vector3d* LinkState::mutable_linear_velocity() {
  set_has_linear_velocity();
  if (linear_velocity_ == NULL) {
    linear_velocity_ = new ::gazebo::msgs::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:salamander.msgs.LinkState.linear_velocity)
  return linear_velocity_;
}
::gazebo::msgs::Vector3d* LinkState::release_linear_velocity() {
  // @@protoc_insertion_point(field_release:salamander.msgs.LinkState.linear_velocity)
  clear_has_linear_velocity();
  ::gazebo::msgs::Vector3d* temp = linear_velocity_;
  linear_velocity_ = NULL;
  return temp;
}
void LinkState::set_allocated_linear_velocity(::gazebo::msgs::Vector3d* linear_velocity) {
  delete linear_velocity_;
  linear_velocity_ = linear_velocity;
  if (linear_velocity) {
    set_has_linear_velocity();
  } else {
    clear_has_linear_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.LinkState.linear_velocity)
}

// optional .gazebo.msgs.Vector3d angular_velocity = 4;
bool LinkState::has_angular_velocity() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void LinkState::set_has_angular_velocity() {
  _has_bits_[0] |= 0x00000008u;
}
void LinkState::clear_has_angular_velocity() {
  _has_bits_[0] &= ~0x00000008u;
}
void LinkState::clear_angular_velocity() {
  if (angular_velocity_ != NULL) angular_velocity_->::gazebo::msgs::Vector3d::Clear();
  clear_has_angular_velocity();
}
const ::gazebo::msgs::Vector3d& LinkState::angular_velocity() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.LinkState.angular_velocity)
  return angular_velocity_ != NULL ? *angular_velocity_ : *default_instance_->angular_velocity_;
}
::gazebo::msgs::Vector3d* LinkState::mutable_angular_velocity() {
  set_has_angular_velocity();
  if (angular_velocity_ == NULL) {
    angular_velocity_ = new ::gazebo::msgs::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:salamander.msgs.LinkState.angular_velocity)
  return angular_velocity_;
}
::gazebo::msgs::Vector3d* LinkState::release_angular_velocity() {
  // @@protoc_insertion_point(field_release:salamander.msgs.LinkState.angular_velocity)
  clear_has_angular_velocity();
  ::gazebo::msgs::Vector3d* temp = angular_velocity_;
  angular_velocity_ = NULL;
  return temp;
}
void LinkState::set_allocated_angular_velocity(::gazebo::msgs::Vector3d* angular_velocity) {
  delete angular_velocity_;
  angular_velocity_ = angular_velocity;
  if (angular_velocity) {
    set_has_angular_velocity();
  } else {
    clear_has_angular_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.LinkState.angular_velocity)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JointsKinematics::kNameFieldNumber;
const int JointsKinematics::kJointFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JointsKinematics::JointsKinematics()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:salamander.msgs.JointsKinematics)
}

void JointsKinematics::InitAsDefaultInstance() {
}

JointsKinematics::JointsKinematics(const JointsKinematics& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:salamander.msgs.JointsKinematics)
}

void JointsKinematics::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

JointsKinematics::~JointsKinematics() {
  // @@protoc_insertion_point(destructor:salamander.msgs.JointsKinematics)
  SharedDtor();
}

void JointsKinematics::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void JointsKinematics::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JointsKinematics::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return JointsKinematics_descriptor_;
}

const JointsKinematics& JointsKinematics::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_log_5fkinematics_2eproto();
  return *default_instance_;
}

JointsKinematics* JointsKinematics::default_instance_ = NULL;

JointsKinematics* JointsKinematics::New(::google::protobuf::Arena* arena) const {
  JointsKinematics* n = new JointsKinematics;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void JointsKinematics::Clear() {
// @@protoc_insertion_point(message_clear_start:salamander.msgs.JointsKinematics)
  if (has_name()) {
    name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  joint_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool JointsKinematics::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:salamander.msgs.JointsKinematics)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "salamander.msgs.JointsKinematics.name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_joint;
        break;
      }

      // repeated .gazebo.msgs.Joint joint = 2;
      case 2: {
        if (tag == 18) {
         parse_joint:
          DO_(input->IncrementRecursionDepth());
         parse_loop_joint:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_joint()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_joint;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:salamander.msgs.JointsKinematics)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:salamander.msgs.JointsKinematics)
  return false;
#undef DO_
}

void JointsKinematics::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:salamander.msgs.JointsKinematics)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "salamander.msgs.JointsKinematics.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // repeated .gazebo.msgs.Joint joint = 2;
  for (unsigned int i = 0, n = this->joint_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->joint(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:salamander.msgs.JointsKinematics)
}

::google::protobuf::uint8* JointsKinematics::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:salamander.msgs.JointsKinematics)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "salamander.msgs.JointsKinematics.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // repeated .gazebo.msgs.Joint joint = 2;
  for (unsigned int i = 0, n = this->joint_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->joint(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:salamander.msgs.JointsKinematics)
  return target;
}

int JointsKinematics::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:salamander.msgs.JointsKinematics)
  int total_size = 0;

  // required string name = 1;
  if (has_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }
  // repeated .gazebo.msgs.Joint joint = 2;
  total_size += 1 * this->joint_size();
  for (int i = 0; i < this->joint_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->joint(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JointsKinematics::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:salamander.msgs.JointsKinematics)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const JointsKinematics* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const JointsKinematics>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:salamander.msgs.JointsKinematics)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:salamander.msgs.JointsKinematics)
    MergeFrom(*source);
  }
}

void JointsKinematics::MergeFrom(const JointsKinematics& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:salamander.msgs.JointsKinematics)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  joint_.MergeFrom(from.joint_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void JointsKinematics::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:salamander.msgs.JointsKinematics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JointsKinematics::CopyFrom(const JointsKinematics& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:salamander.msgs.JointsKinematics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JointsKinematics::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->joint())) return false;
  return true;
}

void JointsKinematics::Swap(JointsKinematics* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JointsKinematics::InternalSwap(JointsKinematics* other) {
  name_.Swap(&other->name_);
  joint_.UnsafeArenaSwap(&other->joint_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata JointsKinematics::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = JointsKinematics_descriptor_;
  metadata.reflection = JointsKinematics_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// JointsKinematics

// required string name = 1;
bool JointsKinematics::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void JointsKinematics::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
void JointsKinematics::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void JointsKinematics::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
 const ::std::string& JointsKinematics::name() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointsKinematics.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void JointsKinematics::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:salamander.msgs.JointsKinematics.name)
}
 void JointsKinematics::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:salamander.msgs.JointsKinematics.name)
}
 void JointsKinematics::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:salamander.msgs.JointsKinematics.name)
}
 ::std::string* JointsKinematics::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointsKinematics.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* JointsKinematics::release_name() {
  // @@protoc_insertion_point(field_release:salamander.msgs.JointsKinematics.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void JointsKinematics::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.JointsKinematics.name)
}

// repeated .gazebo.msgs.Joint joint = 2;
int JointsKinematics::joint_size() const {
  return joint_.size();
}
void JointsKinematics::clear_joint() {
  joint_.Clear();
}
const ::gazebo::msgs::Joint& JointsKinematics::joint(int index) const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointsKinematics.joint)
  return joint_.Get(index);
}
::gazebo::msgs::Joint* JointsKinematics::mutable_joint(int index) {
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointsKinematics.joint)
  return joint_.Mutable(index);
}
::gazebo::msgs::Joint* JointsKinematics::add_joint() {
  // @@protoc_insertion_point(field_add:salamander.msgs.JointsKinematics.joint)
  return joint_.Add();
}
::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Joint >*
JointsKinematics::mutable_joint() {
  // @@protoc_insertion_point(field_mutable_list:salamander.msgs.JointsKinematics.joint)
  return &joint_;
}
const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Joint >&
JointsKinematics::joint() const {
  // @@protoc_insertion_point(field_list:salamander.msgs.JointsKinematics.joint)
  return joint_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace salamander

// @@protoc_insertion_point(global_scope)
