// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salamander_control.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "salamander_control.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace salamander {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* SalamanderControl_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SalamanderControl_reflection_ = NULL;
const ::google::protobuf::Descriptor* JointControl_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  JointControl_reflection_ = NULL;
const ::google::protobuf::Descriptor* JointCommands_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  JointCommands_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_salamander_5fcontrol_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_salamander_5fcontrol_2eproto() {
  protobuf_AddDesc_salamander_5fcontrol_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "salamander_control.proto");
  GOOGLE_CHECK(file != NULL);
  SalamanderControl_descriptor_ = file->message_type(0);
  static const int SalamanderControl_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SalamanderControl, joints_),
  };
  SalamanderControl_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SalamanderControl_descriptor_,
      SalamanderControl::default_instance_,
      SalamanderControl_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SalamanderControl, _has_bits_[0]),
      -1,
      -1,
      sizeof(SalamanderControl),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SalamanderControl, _internal_metadata_),
      -1);
  JointControl_descriptor_ = file->message_type(1);
  static const int JointControl_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointControl, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointControl, control_),
  };
  JointControl_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      JointControl_descriptor_,
      JointControl::default_instance_,
      JointControl_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointControl, _has_bits_[0]),
      -1,
      -1,
      sizeof(JointControl),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointControl, _internal_metadata_),
      -1);
  JointCommands_descriptor_ = file->message_type(2);
  static const int JointCommands_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointCommands, time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointCommands, commands_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointCommands, torque_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointCommands, consumption_),
  };
  JointCommands_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      JointCommands_descriptor_,
      JointCommands::default_instance_,
      JointCommands_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointCommands, _has_bits_[0]),
      -1,
      -1,
      sizeof(JointCommands),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointCommands, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_salamander_5fcontrol_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SalamanderControl_descriptor_, &SalamanderControl::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      JointControl_descriptor_, &JointControl::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      JointCommands_descriptor_, &JointCommands::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_salamander_5fcontrol_2eproto() {
  delete SalamanderControl::default_instance_;
  delete SalamanderControl_reflection_;
  delete JointControl::default_instance_;
  delete JointControl_reflection_;
  delete JointCommands::default_instance_;
  delete JointCommands_reflection_;
}

void protobuf_AddDesc_salamander_5fcontrol_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_salamander_5fcontrol_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::gazebo::msgs::protobuf_AddDesc_time_2eproto();
  ::salamander::msgs::protobuf_AddDesc_salamander_5fjoints_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030salamander_control.proto\022\017salamander.m"
    "sgs\032\ntime.proto\032\027salamander_joints.proto"
    "\"B\n\021SalamanderControl\022-\n\006joints\030\001 \003(\0132\035."
    "salamander.msgs.JointControl\"M\n\014JointCon"
    "trol\022\014\n\004name\030\001 \002(\t\022/\n\007control\030\002 \003(\0132\036.sa"
    "lamander.msgs.JointCommands\"\202\001\n\rJointCom"
    "mands\022\037\n\004time\030\001 \002(\0132\021.gazebo.msgs.Time\022+"
    "\n\010commands\030\002 \002(\0132\031.salamander.msgs.Joint"
    "Cmd\022\016\n\006torque\030\003 \002(\001\022\023\n\013consumption\030\004 \001(\001", 360);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "salamander_control.proto", &protobuf_RegisterTypes);
  SalamanderControl::default_instance_ = new SalamanderControl();
  JointControl::default_instance_ = new JointControl();
  JointCommands::default_instance_ = new JointCommands();
  SalamanderControl::default_instance_->InitAsDefaultInstance();
  JointControl::default_instance_->InitAsDefaultInstance();
  JointCommands::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_salamander_5fcontrol_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_salamander_5fcontrol_2eproto {
  StaticDescriptorInitializer_salamander_5fcontrol_2eproto() {
    protobuf_AddDesc_salamander_5fcontrol_2eproto();
  }
} static_descriptor_initializer_salamander_5fcontrol_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SalamanderControl::kJointsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SalamanderControl::SalamanderControl()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:salamander.msgs.SalamanderControl)
}

void SalamanderControl::InitAsDefaultInstance() {
}

SalamanderControl::SalamanderControl(const SalamanderControl& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:salamander.msgs.SalamanderControl)
}

void SalamanderControl::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SalamanderControl::~SalamanderControl() {
  // @@protoc_insertion_point(destructor:salamander.msgs.SalamanderControl)
  SharedDtor();
}

void SalamanderControl::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SalamanderControl::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SalamanderControl::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SalamanderControl_descriptor_;
}

const SalamanderControl& SalamanderControl::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_salamander_5fcontrol_2eproto();
  return *default_instance_;
}

SalamanderControl* SalamanderControl::default_instance_ = NULL;

SalamanderControl* SalamanderControl::New(::google::protobuf::Arena* arena) const {
  SalamanderControl* n = new SalamanderControl;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SalamanderControl::Clear() {
// @@protoc_insertion_point(message_clear_start:salamander.msgs.SalamanderControl)
  joints_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool SalamanderControl::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:salamander.msgs.SalamanderControl)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .salamander.msgs.JointControl joints = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_joints:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_joints()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_joints;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:salamander.msgs.SalamanderControl)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:salamander.msgs.SalamanderControl)
  return false;
#undef DO_
}

void SalamanderControl::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:salamander.msgs.SalamanderControl)
  // repeated .salamander.msgs.JointControl joints = 1;
  for (unsigned int i = 0, n = this->joints_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->joints(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:salamander.msgs.SalamanderControl)
}

::google::protobuf::uint8* SalamanderControl::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:salamander.msgs.SalamanderControl)
  // repeated .salamander.msgs.JointControl joints = 1;
  for (unsigned int i = 0, n = this->joints_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->joints(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:salamander.msgs.SalamanderControl)
  return target;
}

int SalamanderControl::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:salamander.msgs.SalamanderControl)
  int total_size = 0;

  // repeated .salamander.msgs.JointControl joints = 1;
  total_size += 1 * this->joints_size();
  for (int i = 0; i < this->joints_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->joints(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SalamanderControl::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:salamander.msgs.SalamanderControl)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const SalamanderControl* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SalamanderControl>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:salamander.msgs.SalamanderControl)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:salamander.msgs.SalamanderControl)
    MergeFrom(*source);
  }
}

void SalamanderControl::MergeFrom(const SalamanderControl& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:salamander.msgs.SalamanderControl)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  joints_.MergeFrom(from.joints_);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void SalamanderControl::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:salamander.msgs.SalamanderControl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SalamanderControl::CopyFrom(const SalamanderControl& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:salamander.msgs.SalamanderControl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SalamanderControl::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->joints())) return false;
  return true;
}

void SalamanderControl::Swap(SalamanderControl* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SalamanderControl::InternalSwap(SalamanderControl* other) {
  joints_.UnsafeArenaSwap(&other->joints_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SalamanderControl::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SalamanderControl_descriptor_;
  metadata.reflection = SalamanderControl_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SalamanderControl

// repeated .salamander.msgs.JointControl joints = 1;
int SalamanderControl::joints_size() const {
  return joints_.size();
}
void SalamanderControl::clear_joints() {
  joints_.Clear();
}
const ::salamander::msgs::JointControl& SalamanderControl::joints(int index) const {
  // @@protoc_insertion_point(field_get:salamander.msgs.SalamanderControl.joints)
  return joints_.Get(index);
}
::salamander::msgs::JointControl* SalamanderControl::mutable_joints(int index) {
  // @@protoc_insertion_point(field_mutable:salamander.msgs.SalamanderControl.joints)
  return joints_.Mutable(index);
}
::salamander::msgs::JointControl* SalamanderControl::add_joints() {
  // @@protoc_insertion_point(field_add:salamander.msgs.SalamanderControl.joints)
  return joints_.Add();
}
::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointControl >*
SalamanderControl::mutable_joints() {
  // @@protoc_insertion_point(field_mutable_list:salamander.msgs.SalamanderControl.joints)
  return &joints_;
}
const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointControl >&
SalamanderControl::joints() const {
  // @@protoc_insertion_point(field_list:salamander.msgs.SalamanderControl.joints)
  return joints_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JointControl::kNameFieldNumber;
const int JointControl::kControlFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JointControl::JointControl()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:salamander.msgs.JointControl)
}

void JointControl::InitAsDefaultInstance() {
}

JointControl::JointControl(const JointControl& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:salamander.msgs.JointControl)
}

void JointControl::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

JointControl::~JointControl() {
  // @@protoc_insertion_point(destructor:salamander.msgs.JointControl)
  SharedDtor();
}

void JointControl::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void JointControl::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JointControl::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return JointControl_descriptor_;
}

const JointControl& JointControl::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_salamander_5fcontrol_2eproto();
  return *default_instance_;
}

JointControl* JointControl::default_instance_ = NULL;

JointControl* JointControl::New(::google::protobuf::Arena* arena) const {
  JointControl* n = new JointControl;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void JointControl::Clear() {
// @@protoc_insertion_point(message_clear_start:salamander.msgs.JointControl)
  if (has_name()) {
    name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  control_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool JointControl::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:salamander.msgs.JointControl)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "salamander.msgs.JointControl.name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_control;
        break;
      }

      // repeated .salamander.msgs.JointCommands control = 2;
      case 2: {
        if (tag == 18) {
         parse_control:
          DO_(input->IncrementRecursionDepth());
         parse_loop_control:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_control()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_control;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:salamander.msgs.JointControl)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:salamander.msgs.JointControl)
  return false;
#undef DO_
}

void JointControl::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:salamander.msgs.JointControl)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "salamander.msgs.JointControl.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // repeated .salamander.msgs.JointCommands control = 2;
  for (unsigned int i = 0, n = this->control_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->control(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:salamander.msgs.JointControl)
}

::google::protobuf::uint8* JointControl::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:salamander.msgs.JointControl)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "salamander.msgs.JointControl.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // repeated .salamander.msgs.JointCommands control = 2;
  for (unsigned int i = 0, n = this->control_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->control(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:salamander.msgs.JointControl)
  return target;
}

int JointControl::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:salamander.msgs.JointControl)
  int total_size = 0;

  // required string name = 1;
  if (has_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }
  // repeated .salamander.msgs.JointCommands control = 2;
  total_size += 1 * this->control_size();
  for (int i = 0; i < this->control_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->control(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JointControl::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:salamander.msgs.JointControl)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const JointControl* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const JointControl>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:salamander.msgs.JointControl)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:salamander.msgs.JointControl)
    MergeFrom(*source);
  }
}

void JointControl::MergeFrom(const JointControl& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:salamander.msgs.JointControl)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  control_.MergeFrom(from.control_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void JointControl::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:salamander.msgs.JointControl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JointControl::CopyFrom(const JointControl& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:salamander.msgs.JointControl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JointControl::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->control())) return false;
  return true;
}

void JointControl::Swap(JointControl* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JointControl::InternalSwap(JointControl* other) {
  name_.Swap(&other->name_);
  control_.UnsafeArenaSwap(&other->control_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata JointControl::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = JointControl_descriptor_;
  metadata.reflection = JointControl_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// JointControl

// required string name = 1;
bool JointControl::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void JointControl::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
void JointControl::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void JointControl::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
 const ::std::string& JointControl::name() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointControl.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void JointControl::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:salamander.msgs.JointControl.name)
}
 void JointControl::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:salamander.msgs.JointControl.name)
}
 void JointControl::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:salamander.msgs.JointControl.name)
}
 ::std::string* JointControl::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointControl.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* JointControl::release_name() {
  // @@protoc_insertion_point(field_release:salamander.msgs.JointControl.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void JointControl::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.JointControl.name)
}

// repeated .salamander.msgs.JointCommands control = 2;
int JointControl::control_size() const {
  return control_.size();
}
void JointControl::clear_control() {
  control_.Clear();
}
const ::salamander::msgs::JointCommands& JointControl::control(int index) const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointControl.control)
  return control_.Get(index);
}
::salamander::msgs::JointCommands* JointControl::mutable_control(int index) {
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointControl.control)
  return control_.Mutable(index);
}
::salamander::msgs::JointCommands* JointControl::add_control() {
  // @@protoc_insertion_point(field_add:salamander.msgs.JointControl.control)
  return control_.Add();
}
::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointCommands >*
JointControl::mutable_control() {
  // @@protoc_insertion_point(field_mutable_list:salamander.msgs.JointControl.control)
  return &control_;
}
const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointCommands >&
JointControl::control() const {
  // @@protoc_insertion_point(field_list:salamander.msgs.JointControl.control)
  return control_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JointCommands::kTimeFieldNumber;
const int JointCommands::kCommandsFieldNumber;
const int JointCommands::kTorqueFieldNumber;
const int JointCommands::kConsumptionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JointCommands::JointCommands()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:salamander.msgs.JointCommands)
}

void JointCommands::InitAsDefaultInstance() {
  time_ = const_cast< ::gazebo::msgs::Time*>(&::gazebo::msgs::Time::default_instance());
  commands_ = const_cast< ::salamander::msgs::JointCmd*>(&::salamander::msgs::JointCmd::default_instance());
}

JointCommands::JointCommands(const JointCommands& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:salamander.msgs.JointCommands)
}

void JointCommands::SharedCtor() {
  _cached_size_ = 0;
  time_ = NULL;
  commands_ = NULL;
  torque_ = 0;
  consumption_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

JointCommands::~JointCommands() {
  // @@protoc_insertion_point(destructor:salamander.msgs.JointCommands)
  SharedDtor();
}

void JointCommands::SharedDtor() {
  if (this != default_instance_) {
    delete time_;
    delete commands_;
  }
}

void JointCommands::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JointCommands::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return JointCommands_descriptor_;
}

const JointCommands& JointCommands::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_salamander_5fcontrol_2eproto();
  return *default_instance_;
}

JointCommands* JointCommands::default_instance_ = NULL;

JointCommands* JointCommands::New(::google::protobuf::Arena* arena) const {
  JointCommands* n = new JointCommands;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void JointCommands::Clear() {
// @@protoc_insertion_point(message_clear_start:salamander.msgs.JointCommands)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(JointCommands, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<JointCommands*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 15u) {
    ZR_(torque_, consumption_);
    if (has_time()) {
      if (time_ != NULL) time_->::gazebo::msgs::Time::Clear();
    }
    if (has_commands()) {
      if (commands_ != NULL) commands_->::salamander::msgs::JointCmd::Clear();
    }
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool JointCommands::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:salamander.msgs.JointCommands)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .gazebo.msgs.Time time = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_time()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_commands;
        break;
      }

      // required .salamander.msgs.JointCmd commands = 2;
      case 2: {
        if (tag == 18) {
         parse_commands:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_commands()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_torque;
        break;
      }

      // required double torque = 3;
      case 3: {
        if (tag == 25) {
         parse_torque:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &torque_)));
          set_has_torque();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_consumption;
        break;
      }

      // optional double consumption = 4;
      case 4: {
        if (tag == 33) {
         parse_consumption:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &consumption_)));
          set_has_consumption();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:salamander.msgs.JointCommands)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:salamander.msgs.JointCommands)
  return false;
#undef DO_
}

void JointCommands::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:salamander.msgs.JointCommands)
  // required .gazebo.msgs.Time time = 1;
  if (has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->time_, output);
  }

  // required .salamander.msgs.JointCmd commands = 2;
  if (has_commands()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->commands_, output);
  }

  // required double torque = 3;
  if (has_torque()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->torque(), output);
  }

  // optional double consumption = 4;
  if (has_consumption()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->consumption(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:salamander.msgs.JointCommands)
}

::google::protobuf::uint8* JointCommands::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:salamander.msgs.JointCommands)
  // required .gazebo.msgs.Time time = 1;
  if (has_time()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->time_, false, target);
  }

  // required .salamander.msgs.JointCmd commands = 2;
  if (has_commands()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->commands_, false, target);
  }

  // required double torque = 3;
  if (has_torque()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->torque(), target);
  }

  // optional double consumption = 4;
  if (has_consumption()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->consumption(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:salamander.msgs.JointCommands)
  return target;
}

int JointCommands::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:salamander.msgs.JointCommands)
  int total_size = 0;

  if (has_time()) {
    // required .gazebo.msgs.Time time = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->time_);
  }

  if (has_commands()) {
    // required .salamander.msgs.JointCmd commands = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->commands_);
  }

  if (has_torque()) {
    // required double torque = 3;
    total_size += 1 + 8;
  }

  return total_size;
}
int JointCommands::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:salamander.msgs.JointCommands)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required .gazebo.msgs.Time time = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->time_);

    // required .salamander.msgs.JointCmd commands = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->commands_);

    // required double torque = 3;
    total_size += 1 + 8;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional double consumption = 4;
  if (has_consumption()) {
    total_size += 1 + 8;
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JointCommands::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:salamander.msgs.JointCommands)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const JointCommands* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const JointCommands>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:salamander.msgs.JointCommands)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:salamander.msgs.JointCommands)
    MergeFrom(*source);
  }
}

void JointCommands::MergeFrom(const JointCommands& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:salamander.msgs.JointCommands)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_time()) {
      mutable_time()->::gazebo::msgs::Time::MergeFrom(from.time());
    }
    if (from.has_commands()) {
      mutable_commands()->::salamander::msgs::JointCmd::MergeFrom(from.commands());
    }
    if (from.has_torque()) {
      set_torque(from.torque());
    }
    if (from.has_consumption()) {
      set_consumption(from.consumption());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void JointCommands::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:salamander.msgs.JointCommands)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JointCommands::CopyFrom(const JointCommands& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:salamander.msgs.JointCommands)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JointCommands::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  if (has_time()) {
    if (!this->time_->IsInitialized()) return false;
  }
  if (has_commands()) {
    if (!this->commands_->IsInitialized()) return false;
  }
  return true;
}

void JointCommands::Swap(JointCommands* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JointCommands::InternalSwap(JointCommands* other) {
  std::swap(time_, other->time_);
  std::swap(commands_, other->commands_);
  std::swap(torque_, other->torque_);
  std::swap(consumption_, other->consumption_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata JointCommands::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = JointCommands_descriptor_;
  metadata.reflection = JointCommands_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// JointCommands

// required .gazebo.msgs.Time time = 1;
bool JointCommands::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void JointCommands::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
void JointCommands::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
void JointCommands::clear_time() {
  if (time_ != NULL) time_->::gazebo::msgs::Time::Clear();
  clear_has_time();
}
const ::gazebo::msgs::Time& JointCommands::time() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointCommands.time)
  return time_ != NULL ? *time_ : *default_instance_->time_;
}
::gazebo::msgs::Time* JointCommands::mutable_time() {
  set_has_time();
  if (time_ == NULL) {
    time_ = new ::gazebo::msgs::Time;
  }
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointCommands.time)
  return time_;
}
::gazebo::msgs::Time* JointCommands::release_time() {
  // @@protoc_insertion_point(field_release:salamander.msgs.JointCommands.time)
  clear_has_time();
  ::gazebo::msgs::Time* temp = time_;
  time_ = NULL;
  return temp;
}
void JointCommands::set_allocated_time(::gazebo::msgs::Time* time) {
  delete time_;
  time_ = time;
  if (time) {
    set_has_time();
  } else {
    clear_has_time();
  }
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.JointCommands.time)
}

// required .salamander.msgs.JointCmd commands = 2;
bool JointCommands::has_commands() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void JointCommands::set_has_commands() {
  _has_bits_[0] |= 0x00000002u;
}
void JointCommands::clear_has_commands() {
  _has_bits_[0] &= ~0x00000002u;
}
void JointCommands::clear_commands() {
  if (commands_ != NULL) commands_->::salamander::msgs::JointCmd::Clear();
  clear_has_commands();
}
const ::salamander::msgs::JointCmd& JointCommands::commands() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointCommands.commands)
  return commands_ != NULL ? *commands_ : *default_instance_->commands_;
}
::salamander::msgs::JointCmd* JointCommands::mutable_commands() {
  set_has_commands();
  if (commands_ == NULL) {
    commands_ = new ::salamander::msgs::JointCmd;
  }
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointCommands.commands)
  return commands_;
}
::salamander::msgs::JointCmd* JointCommands::release_commands() {
  // @@protoc_insertion_point(field_release:salamander.msgs.JointCommands.commands)
  clear_has_commands();
  ::salamander::msgs::JointCmd* temp = commands_;
  commands_ = NULL;
  return temp;
}
void JointCommands::set_allocated_commands(::salamander::msgs::JointCmd* commands) {
  delete commands_;
  commands_ = commands;
  if (commands) {
    set_has_commands();
  } else {
    clear_has_commands();
  }
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.JointCommands.commands)
}

// required double torque = 3;
bool JointCommands::has_torque() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void JointCommands::set_has_torque() {
  _has_bits_[0] |= 0x00000004u;
}
void JointCommands::clear_has_torque() {
  _has_bits_[0] &= ~0x00000004u;
}
void JointCommands::clear_torque() {
  torque_ = 0;
  clear_has_torque();
}
 double JointCommands::torque() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointCommands.torque)
  return torque_;
}
 void JointCommands::set_torque(double value) {
  set_has_torque();
  torque_ = value;
  // @@protoc_insertion_point(field_set:salamander.msgs.JointCommands.torque)
}

// optional double consumption = 4;
bool JointCommands::has_consumption() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void JointCommands::set_has_consumption() {
  _has_bits_[0] |= 0x00000008u;
}
void JointCommands::clear_has_consumption() {
  _has_bits_[0] &= ~0x00000008u;
}
void JointCommands::clear_consumption() {
  consumption_ = 0;
  clear_has_consumption();
}
 double JointCommands::consumption() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointCommands.consumption)
  return consumption_;
}
 void JointCommands::set_consumption(double value) {
  set_has_consumption();
  consumption_ = value;
  // @@protoc_insertion_point(field_set:salamander.msgs.JointCommands.consumption)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace salamander

// @@protoc_insertion_point(global_scope)
