// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salamander_joints.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "salamander_joints.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace salamander {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* JointKinematics_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  JointKinematics_reflection_ = NULL;
const ::google::protobuf::Descriptor* JointState_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  JointState_reflection_ = NULL;
const ::google::protobuf::Descriptor* JointTorque_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  JointTorque_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_salamander_5fjoints_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_salamander_5fjoints_2eproto() {
  protobuf_AddDesc_salamander_5fjoints_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "salamander_joints.proto");
  GOOGLE_CHECK(file != NULL);
  JointKinematics_descriptor_ = file->message_type(0);
  static const int JointKinematics_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointKinematics, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointKinematics, state_),
  };
  JointKinematics_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      JointKinematics_descriptor_,
      JointKinematics::default_instance_,
      JointKinematics_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointKinematics, _has_bits_[0]),
      -1,
      -1,
      sizeof(JointKinematics),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointKinematics, _internal_metadata_),
      -1);
  JointState_descriptor_ = file->message_type(1);
  static const int JointState_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointState, time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointState, position_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointState, velocity_),
  };
  JointState_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      JointState_descriptor_,
      JointState::default_instance_,
      JointState_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointState, _has_bits_[0]),
      -1,
      -1,
      sizeof(JointState),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointState, _internal_metadata_),
      -1);
  JointTorque_descriptor_ = file->message_type(2);
  static const int JointTorque_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointTorque, time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointTorque, torque_),
  };
  JointTorque_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      JointTorque_descriptor_,
      JointTorque::default_instance_,
      JointTorque_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointTorque, _has_bits_[0]),
      -1,
      -1,
      sizeof(JointTorque),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JointTorque, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_salamander_5fjoints_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      JointKinematics_descriptor_, &JointKinematics::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      JointState_descriptor_, &JointState::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      JointTorque_descriptor_, &JointTorque::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_salamander_5fjoints_2eproto() {
  delete JointKinematics::default_instance_;
  delete JointKinematics_reflection_;
  delete JointState::default_instance_;
  delete JointState_reflection_;
  delete JointTorque::default_instance_;
  delete JointTorque_reflection_;
}

void protobuf_AddDesc_salamander_5fjoints_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_salamander_5fjoints_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::gazebo::msgs::protobuf_AddDesc_time_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027salamander_joints.proto\022\017salamander.ms"
    "gs\032\ntime.proto\"K\n\017JointKinematics\022\014\n\004nam"
    "e\030\001 \002(\t\022*\n\005state\030\002 \003(\0132\033.salamander.msgs"
    ".JointState\"Q\n\nJointState\022\037\n\004time\030\001 \002(\0132"
    "\021.gazebo.msgs.Time\022\020\n\010position\030\002 \002(\001\022\020\n\010"
    "velocity\030\003 \001(\001\">\n\013JointTorque\022\037\n\004time\030\001 "
    "\002(\0132\021.gazebo.msgs.Time\022\016\n\006torque\030\002 \002(\001", 278);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "salamander_joints.proto", &protobuf_RegisterTypes);
  JointKinematics::default_instance_ = new JointKinematics();
  JointState::default_instance_ = new JointState();
  JointTorque::default_instance_ = new JointTorque();
  JointKinematics::default_instance_->InitAsDefaultInstance();
  JointState::default_instance_->InitAsDefaultInstance();
  JointTorque::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_salamander_5fjoints_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_salamander_5fjoints_2eproto {
  StaticDescriptorInitializer_salamander_5fjoints_2eproto() {
    protobuf_AddDesc_salamander_5fjoints_2eproto();
  }
} static_descriptor_initializer_salamander_5fjoints_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JointKinematics::kNameFieldNumber;
const int JointKinematics::kStateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JointKinematics::JointKinematics()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:salamander.msgs.JointKinematics)
}

void JointKinematics::InitAsDefaultInstance() {
}

JointKinematics::JointKinematics(const JointKinematics& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:salamander.msgs.JointKinematics)
}

void JointKinematics::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

JointKinematics::~JointKinematics() {
  // @@protoc_insertion_point(destructor:salamander.msgs.JointKinematics)
  SharedDtor();
}

void JointKinematics::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void JointKinematics::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JointKinematics::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return JointKinematics_descriptor_;
}

const JointKinematics& JointKinematics::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_salamander_5fjoints_2eproto();
  return *default_instance_;
}

JointKinematics* JointKinematics::default_instance_ = NULL;

JointKinematics* JointKinematics::New(::google::protobuf::Arena* arena) const {
  JointKinematics* n = new JointKinematics;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void JointKinematics::Clear() {
// @@protoc_insertion_point(message_clear_start:salamander.msgs.JointKinematics)
  if (has_name()) {
    name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  state_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool JointKinematics::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:salamander.msgs.JointKinematics)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "salamander.msgs.JointKinematics.name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_state;
        break;
      }

      // repeated .salamander.msgs.JointState state = 2;
      case 2: {
        if (tag == 18) {
         parse_state:
          DO_(input->IncrementRecursionDepth());
         parse_loop_state:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_state()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_state;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:salamander.msgs.JointKinematics)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:salamander.msgs.JointKinematics)
  return false;
#undef DO_
}

void JointKinematics::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:salamander.msgs.JointKinematics)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "salamander.msgs.JointKinematics.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // repeated .salamander.msgs.JointState state = 2;
  for (unsigned int i = 0, n = this->state_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->state(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:salamander.msgs.JointKinematics)
}

::google::protobuf::uint8* JointKinematics::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:salamander.msgs.JointKinematics)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "salamander.msgs.JointKinematics.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // repeated .salamander.msgs.JointState state = 2;
  for (unsigned int i = 0, n = this->state_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->state(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:salamander.msgs.JointKinematics)
  return target;
}

int JointKinematics::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:salamander.msgs.JointKinematics)
  int total_size = 0;

  // required string name = 1;
  if (has_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }
  // repeated .salamander.msgs.JointState state = 2;
  total_size += 1 * this->state_size();
  for (int i = 0; i < this->state_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->state(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JointKinematics::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:salamander.msgs.JointKinematics)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const JointKinematics* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const JointKinematics>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:salamander.msgs.JointKinematics)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:salamander.msgs.JointKinematics)
    MergeFrom(*source);
  }
}

void JointKinematics::MergeFrom(const JointKinematics& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:salamander.msgs.JointKinematics)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  state_.MergeFrom(from.state_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void JointKinematics::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:salamander.msgs.JointKinematics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JointKinematics::CopyFrom(const JointKinematics& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:salamander.msgs.JointKinematics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JointKinematics::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->state())) return false;
  return true;
}

void JointKinematics::Swap(JointKinematics* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JointKinematics::InternalSwap(JointKinematics* other) {
  name_.Swap(&other->name_);
  state_.UnsafeArenaSwap(&other->state_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata JointKinematics::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = JointKinematics_descriptor_;
  metadata.reflection = JointKinematics_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// JointKinematics

// required string name = 1;
bool JointKinematics::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void JointKinematics::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
void JointKinematics::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void JointKinematics::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
 const ::std::string& JointKinematics::name() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointKinematics.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void JointKinematics::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:salamander.msgs.JointKinematics.name)
}
 void JointKinematics::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:salamander.msgs.JointKinematics.name)
}
 void JointKinematics::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:salamander.msgs.JointKinematics.name)
}
 ::std::string* JointKinematics::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointKinematics.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* JointKinematics::release_name() {
  // @@protoc_insertion_point(field_release:salamander.msgs.JointKinematics.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void JointKinematics::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.JointKinematics.name)
}

// repeated .salamander.msgs.JointState state = 2;
int JointKinematics::state_size() const {
  return state_.size();
}
void JointKinematics::clear_state() {
  state_.Clear();
}
const ::salamander::msgs::JointState& JointKinematics::state(int index) const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointKinematics.state)
  return state_.Get(index);
}
::salamander::msgs::JointState* JointKinematics::mutable_state(int index) {
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointKinematics.state)
  return state_.Mutable(index);
}
::salamander::msgs::JointState* JointKinematics::add_state() {
  // @@protoc_insertion_point(field_add:salamander.msgs.JointKinematics.state)
  return state_.Add();
}
::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointState >*
JointKinematics::mutable_state() {
  // @@protoc_insertion_point(field_mutable_list:salamander.msgs.JointKinematics.state)
  return &state_;
}
const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointState >&
JointKinematics::state() const {
  // @@protoc_insertion_point(field_list:salamander.msgs.JointKinematics.state)
  return state_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JointState::kTimeFieldNumber;
const int JointState::kPositionFieldNumber;
const int JointState::kVelocityFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JointState::JointState()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:salamander.msgs.JointState)
}

void JointState::InitAsDefaultInstance() {
  time_ = const_cast< ::gazebo::msgs::Time*>(&::gazebo::msgs::Time::default_instance());
}

JointState::JointState(const JointState& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:salamander.msgs.JointState)
}

void JointState::SharedCtor() {
  _cached_size_ = 0;
  time_ = NULL;
  position_ = 0;
  velocity_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

JointState::~JointState() {
  // @@protoc_insertion_point(destructor:salamander.msgs.JointState)
  SharedDtor();
}

void JointState::SharedDtor() {
  if (this != default_instance_) {
    delete time_;
  }
}

void JointState::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JointState::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return JointState_descriptor_;
}

const JointState& JointState::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_salamander_5fjoints_2eproto();
  return *default_instance_;
}

JointState* JointState::default_instance_ = NULL;

JointState* JointState::New(::google::protobuf::Arena* arena) const {
  JointState* n = new JointState;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void JointState::Clear() {
// @@protoc_insertion_point(message_clear_start:salamander.msgs.JointState)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(JointState, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<JointState*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 7u) {
    ZR_(position_, velocity_);
    if (has_time()) {
      if (time_ != NULL) time_->::gazebo::msgs::Time::Clear();
    }
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool JointState::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:salamander.msgs.JointState)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .gazebo.msgs.Time time = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_time()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_position;
        break;
      }

      // required double position = 2;
      case 2: {
        if (tag == 17) {
         parse_position:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &position_)));
          set_has_position();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_velocity;
        break;
      }

      // optional double velocity = 3;
      case 3: {
        if (tag == 25) {
         parse_velocity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &velocity_)));
          set_has_velocity();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:salamander.msgs.JointState)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:salamander.msgs.JointState)
  return false;
#undef DO_
}

void JointState::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:salamander.msgs.JointState)
  // required .gazebo.msgs.Time time = 1;
  if (has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->time_, output);
  }

  // required double position = 2;
  if (has_position()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->position(), output);
  }

  // optional double velocity = 3;
  if (has_velocity()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->velocity(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:salamander.msgs.JointState)
}

::google::protobuf::uint8* JointState::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:salamander.msgs.JointState)
  // required .gazebo.msgs.Time time = 1;
  if (has_time()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->time_, false, target);
  }

  // required double position = 2;
  if (has_position()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->position(), target);
  }

  // optional double velocity = 3;
  if (has_velocity()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->velocity(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:salamander.msgs.JointState)
  return target;
}

int JointState::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:salamander.msgs.JointState)
  int total_size = 0;

  if (has_time()) {
    // required .gazebo.msgs.Time time = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->time_);
  }

  if (has_position()) {
    // required double position = 2;
    total_size += 1 + 8;
  }

  return total_size;
}
int JointState::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:salamander.msgs.JointState)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required .gazebo.msgs.Time time = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->time_);

    // required double position = 2;
    total_size += 1 + 8;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional double velocity = 3;
  if (has_velocity()) {
    total_size += 1 + 8;
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JointState::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:salamander.msgs.JointState)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const JointState* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const JointState>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:salamander.msgs.JointState)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:salamander.msgs.JointState)
    MergeFrom(*source);
  }
}

void JointState::MergeFrom(const JointState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:salamander.msgs.JointState)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_time()) {
      mutable_time()->::gazebo::msgs::Time::MergeFrom(from.time());
    }
    if (from.has_position()) {
      set_position(from.position());
    }
    if (from.has_velocity()) {
      set_velocity(from.velocity());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void JointState::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:salamander.msgs.JointState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JointState::CopyFrom(const JointState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:salamander.msgs.JointState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JointState::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_time()) {
    if (!this->time_->IsInitialized()) return false;
  }
  return true;
}

void JointState::Swap(JointState* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JointState::InternalSwap(JointState* other) {
  std::swap(time_, other->time_);
  std::swap(position_, other->position_);
  std::swap(velocity_, other->velocity_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata JointState::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = JointState_descriptor_;
  metadata.reflection = JointState_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// JointState

// required .gazebo.msgs.Time time = 1;
bool JointState::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void JointState::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
void JointState::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
void JointState::clear_time() {
  if (time_ != NULL) time_->::gazebo::msgs::Time::Clear();
  clear_has_time();
}
const ::gazebo::msgs::Time& JointState::time() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointState.time)
  return time_ != NULL ? *time_ : *default_instance_->time_;
}
::gazebo::msgs::Time* JointState::mutable_time() {
  set_has_time();
  if (time_ == NULL) {
    time_ = new ::gazebo::msgs::Time;
  }
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointState.time)
  return time_;
}
::gazebo::msgs::Time* JointState::release_time() {
  // @@protoc_insertion_point(field_release:salamander.msgs.JointState.time)
  clear_has_time();
  ::gazebo::msgs::Time* temp = time_;
  time_ = NULL;
  return temp;
}
void JointState::set_allocated_time(::gazebo::msgs::Time* time) {
  delete time_;
  time_ = time;
  if (time) {
    set_has_time();
  } else {
    clear_has_time();
  }
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.JointState.time)
}

// required double position = 2;
bool JointState::has_position() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void JointState::set_has_position() {
  _has_bits_[0] |= 0x00000002u;
}
void JointState::clear_has_position() {
  _has_bits_[0] &= ~0x00000002u;
}
void JointState::clear_position() {
  position_ = 0;
  clear_has_position();
}
 double JointState::position() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointState.position)
  return position_;
}
 void JointState::set_position(double value) {
  set_has_position();
  position_ = value;
  // @@protoc_insertion_point(field_set:salamander.msgs.JointState.position)
}

// optional double velocity = 3;
bool JointState::has_velocity() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void JointState::set_has_velocity() {
  _has_bits_[0] |= 0x00000004u;
}
void JointState::clear_has_velocity() {
  _has_bits_[0] &= ~0x00000004u;
}
void JointState::clear_velocity() {
  velocity_ = 0;
  clear_has_velocity();
}
 double JointState::velocity() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointState.velocity)
  return velocity_;
}
 void JointState::set_velocity(double value) {
  set_has_velocity();
  velocity_ = value;
  // @@protoc_insertion_point(field_set:salamander.msgs.JointState.velocity)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JointTorque::kTimeFieldNumber;
const int JointTorque::kTorqueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JointTorque::JointTorque()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:salamander.msgs.JointTorque)
}

void JointTorque::InitAsDefaultInstance() {
  time_ = const_cast< ::gazebo::msgs::Time*>(&::gazebo::msgs::Time::default_instance());
}

JointTorque::JointTorque(const JointTorque& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:salamander.msgs.JointTorque)
}

void JointTorque::SharedCtor() {
  _cached_size_ = 0;
  time_ = NULL;
  torque_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

JointTorque::~JointTorque() {
  // @@protoc_insertion_point(destructor:salamander.msgs.JointTorque)
  SharedDtor();
}

void JointTorque::SharedDtor() {
  if (this != default_instance_) {
    delete time_;
  }
}

void JointTorque::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JointTorque::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return JointTorque_descriptor_;
}

const JointTorque& JointTorque::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_salamander_5fjoints_2eproto();
  return *default_instance_;
}

JointTorque* JointTorque::default_instance_ = NULL;

JointTorque* JointTorque::New(::google::protobuf::Arena* arena) const {
  JointTorque* n = new JointTorque;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void JointTorque::Clear() {
// @@protoc_insertion_point(message_clear_start:salamander.msgs.JointTorque)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_time()) {
      if (time_ != NULL) time_->::gazebo::msgs::Time::Clear();
    }
    torque_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool JointTorque::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:salamander.msgs.JointTorque)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .gazebo.msgs.Time time = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_time()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_torque;
        break;
      }

      // required double torque = 2;
      case 2: {
        if (tag == 17) {
         parse_torque:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &torque_)));
          set_has_torque();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:salamander.msgs.JointTorque)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:salamander.msgs.JointTorque)
  return false;
#undef DO_
}

void JointTorque::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:salamander.msgs.JointTorque)
  // required .gazebo.msgs.Time time = 1;
  if (has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->time_, output);
  }

  // required double torque = 2;
  if (has_torque()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->torque(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:salamander.msgs.JointTorque)
}

::google::protobuf::uint8* JointTorque::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:salamander.msgs.JointTorque)
  // required .gazebo.msgs.Time time = 1;
  if (has_time()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->time_, false, target);
  }

  // required double torque = 2;
  if (has_torque()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->torque(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:salamander.msgs.JointTorque)
  return target;
}

int JointTorque::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:salamander.msgs.JointTorque)
  int total_size = 0;

  if (has_time()) {
    // required .gazebo.msgs.Time time = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->time_);
  }

  if (has_torque()) {
    // required double torque = 2;
    total_size += 1 + 8;
  }

  return total_size;
}
int JointTorque::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:salamander.msgs.JointTorque)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required .gazebo.msgs.Time time = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->time_);

    // required double torque = 2;
    total_size += 1 + 8;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JointTorque::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:salamander.msgs.JointTorque)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const JointTorque* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const JointTorque>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:salamander.msgs.JointTorque)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:salamander.msgs.JointTorque)
    MergeFrom(*source);
  }
}

void JointTorque::MergeFrom(const JointTorque& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:salamander.msgs.JointTorque)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_time()) {
      mutable_time()->::gazebo::msgs::Time::MergeFrom(from.time());
    }
    if (from.has_torque()) {
      set_torque(from.torque());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void JointTorque::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:salamander.msgs.JointTorque)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JointTorque::CopyFrom(const JointTorque& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:salamander.msgs.JointTorque)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JointTorque::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_time()) {
    if (!this->time_->IsInitialized()) return false;
  }
  return true;
}

void JointTorque::Swap(JointTorque* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JointTorque::InternalSwap(JointTorque* other) {
  std::swap(time_, other->time_);
  std::swap(torque_, other->torque_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata JointTorque::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = JointTorque_descriptor_;
  metadata.reflection = JointTorque_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// JointTorque

// required .gazebo.msgs.Time time = 1;
bool JointTorque::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void JointTorque::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
void JointTorque::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
void JointTorque::clear_time() {
  if (time_ != NULL) time_->::gazebo::msgs::Time::Clear();
  clear_has_time();
}
const ::gazebo::msgs::Time& JointTorque::time() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointTorque.time)
  return time_ != NULL ? *time_ : *default_instance_->time_;
}
::gazebo::msgs::Time* JointTorque::mutable_time() {
  set_has_time();
  if (time_ == NULL) {
    time_ = new ::gazebo::msgs::Time;
  }
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointTorque.time)
  return time_;
}
::gazebo::msgs::Time* JointTorque::release_time() {
  // @@protoc_insertion_point(field_release:salamander.msgs.JointTorque.time)
  clear_has_time();
  ::gazebo::msgs::Time* temp = time_;
  time_ = NULL;
  return temp;
}
void JointTorque::set_allocated_time(::gazebo::msgs::Time* time) {
  delete time_;
  time_ = time;
  if (time) {
    set_has_time();
  } else {
    clear_has_time();
  }
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.JointTorque.time)
}

// required double torque = 2;
bool JointTorque::has_torque() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void JointTorque::set_has_torque() {
  _has_bits_[0] |= 0x00000002u;
}
void JointTorque::clear_has_torque() {
  _has_bits_[0] &= ~0x00000002u;
}
void JointTorque::clear_torque() {
  torque_ = 0;
  clear_has_torque();
}
 double JointTorque::torque() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointTorque.torque)
  return torque_;
}
 void JointTorque::set_torque(double value) {
  set_has_torque();
  torque_ = value;
  // @@protoc_insertion_point(field_set:salamander.msgs.JointTorque.torque)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace salamander

// @@protoc_insertion_point(global_scope)
