// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salamander_control.proto

#ifndef PROTOBUF_salamander_5fcontrol_2eproto__INCLUDED
#define PROTOBUF_salamander_5fcontrol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "salamander_joints.pb.h"
// @@protoc_insertion_point(includes)

namespace salamander {
namespace msgs {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_salamander_5fcontrol_2eproto();
void protobuf_AssignDesc_salamander_5fcontrol_2eproto();
void protobuf_ShutdownFile_salamander_5fcontrol_2eproto();

class ControlAnalysis;
class JointCommands;
class JointConsumption;
class JointTorques;
class SalamanderControl;

// ===================================================================

class SalamanderControl : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:salamander.msgs.SalamanderControl) */ {
 public:
  SalamanderControl();
  virtual ~SalamanderControl();

  SalamanderControl(const SalamanderControl& from);

  inline SalamanderControl& operator=(const SalamanderControl& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SalamanderControl& default_instance();

  void Swap(SalamanderControl* other);

  // implements Message ----------------------------------------------

  inline SalamanderControl* New() const { return New(NULL); }

  SalamanderControl* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SalamanderControl& from);
  void MergeFrom(const SalamanderControl& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SalamanderControl* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .salamander.msgs.JointCommands cmds = 1;
  int cmds_size() const;
  void clear_cmds();
  static const int kCmdsFieldNumber = 1;
  const ::salamander::msgs::JointCommands& cmds(int index) const;
  ::salamander::msgs::JointCommands* mutable_cmds(int index);
  ::salamander::msgs::JointCommands* add_cmds();
  ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointCommands >*
      mutable_cmds();
  const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointCommands >&
      cmds() const;

  // repeated .salamander.msgs.JointTorques torques = 2;
  int torques_size() const;
  void clear_torques();
  static const int kTorquesFieldNumber = 2;
  const ::salamander::msgs::JointTorques& torques(int index) const;
  ::salamander::msgs::JointTorques* mutable_torques(int index);
  ::salamander::msgs::JointTorques* add_torques();
  ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointTorques >*
      mutable_torques();
  const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointTorques >&
      torques() const;

  // optional .salamander.msgs.ControlAnalysis analysis = 3;
  bool has_analysis() const;
  void clear_analysis();
  static const int kAnalysisFieldNumber = 3;
  const ::salamander::msgs::ControlAnalysis& analysis() const;
  ::salamander::msgs::ControlAnalysis* mutable_analysis();
  ::salamander::msgs::ControlAnalysis* release_analysis();
  void set_allocated_analysis(::salamander::msgs::ControlAnalysis* analysis);

  // @@protoc_insertion_point(class_scope:salamander.msgs.SalamanderControl)
 private:
  inline void set_has_analysis();
  inline void clear_has_analysis();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointCommands > cmds_;
  ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointTorques > torques_;
  ::salamander::msgs::ControlAnalysis* analysis_;
  friend void  protobuf_AddDesc_salamander_5fcontrol_2eproto();
  friend void protobuf_AssignDesc_salamander_5fcontrol_2eproto();
  friend void protobuf_ShutdownFile_salamander_5fcontrol_2eproto();

  void InitAsDefaultInstance();
  static SalamanderControl* default_instance_;
};
// -------------------------------------------------------------------

class ControlAnalysis : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:salamander.msgs.ControlAnalysis) */ {
 public:
  ControlAnalysis();
  virtual ~ControlAnalysis();

  ControlAnalysis(const ControlAnalysis& from);

  inline ControlAnalysis& operator=(const ControlAnalysis& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ControlAnalysis& default_instance();

  void Swap(ControlAnalysis* other);

  // implements Message ----------------------------------------------

  inline ControlAnalysis* New() const { return New(NULL); }

  ControlAnalysis* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ControlAnalysis& from);
  void MergeFrom(const ControlAnalysis& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ControlAnalysis* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .salamander.msgs.JointConsumption joints_consumption = 1;
  int joints_consumption_size() const;
  void clear_joints_consumption();
  static const int kJointsConsumptionFieldNumber = 1;
  const ::salamander::msgs::JointConsumption& joints_consumption(int index) const;
  ::salamander::msgs::JointConsumption* mutable_joints_consumption(int index);
  ::salamander::msgs::JointConsumption* add_joints_consumption();
  ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointConsumption >*
      mutable_joints_consumption();
  const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointConsumption >&
      joints_consumption() const;

  // @@protoc_insertion_point(class_scope:salamander.msgs.ControlAnalysis)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointConsumption > joints_consumption_;
  friend void  protobuf_AddDesc_salamander_5fcontrol_2eproto();
  friend void protobuf_AssignDesc_salamander_5fcontrol_2eproto();
  friend void protobuf_ShutdownFile_salamander_5fcontrol_2eproto();

  void InitAsDefaultInstance();
  static ControlAnalysis* default_instance_;
};
// -------------------------------------------------------------------

class JointConsumption : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:salamander.msgs.JointConsumption) */ {
 public:
  JointConsumption();
  virtual ~JointConsumption();

  JointConsumption(const JointConsumption& from);

  inline JointConsumption& operator=(const JointConsumption& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JointConsumption& default_instance();

  void Swap(JointConsumption* other);

  // implements Message ----------------------------------------------

  inline JointConsumption* New() const { return New(NULL); }

  JointConsumption* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JointConsumption& from);
  void MergeFrom(const JointConsumption& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(JointConsumption* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required double consumption = 2;
  bool has_consumption() const;
  void clear_consumption();
  static const int kConsumptionFieldNumber = 2;
  double consumption() const;
  void set_consumption(double value);

  // @@protoc_insertion_point(class_scope:salamander.msgs.JointConsumption)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_consumption();
  inline void clear_has_consumption();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  double consumption_;
  friend void  protobuf_AddDesc_salamander_5fcontrol_2eproto();
  friend void protobuf_AssignDesc_salamander_5fcontrol_2eproto();
  friend void protobuf_ShutdownFile_salamander_5fcontrol_2eproto();

  void InitAsDefaultInstance();
  static JointConsumption* default_instance_;
};
// -------------------------------------------------------------------

class JointCommands : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:salamander.msgs.JointCommands) */ {
 public:
  JointCommands();
  virtual ~JointCommands();

  JointCommands(const JointCommands& from);

  inline JointCommands& operator=(const JointCommands& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JointCommands& default_instance();

  void Swap(JointCommands* other);

  // implements Message ----------------------------------------------

  inline JointCommands* New() const { return New(NULL); }

  JointCommands* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JointCommands& from);
  void MergeFrom(const JointCommands& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(JointCommands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // repeated .salamander.msgs.JointState commands = 2;
  int commands_size() const;
  void clear_commands();
  static const int kCommandsFieldNumber = 2;
  const ::salamander::msgs::JointState& commands(int index) const;
  ::salamander::msgs::JointState* mutable_commands(int index);
  ::salamander::msgs::JointState* add_commands();
  ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointState >*
      mutable_commands();
  const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointState >&
      commands() const;

  // @@protoc_insertion_point(class_scope:salamander.msgs.JointCommands)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointState > commands_;
  friend void  protobuf_AddDesc_salamander_5fcontrol_2eproto();
  friend void protobuf_AssignDesc_salamander_5fcontrol_2eproto();
  friend void protobuf_ShutdownFile_salamander_5fcontrol_2eproto();

  void InitAsDefaultInstance();
  static JointCommands* default_instance_;
};
// -------------------------------------------------------------------

class JointTorques : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:salamander.msgs.JointTorques) */ {
 public:
  JointTorques();
  virtual ~JointTorques();

  JointTorques(const JointTorques& from);

  inline JointTorques& operator=(const JointTorques& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JointTorques& default_instance();

  void Swap(JointTorques* other);

  // implements Message ----------------------------------------------

  inline JointTorques* New() const { return New(NULL); }

  JointTorques* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JointTorques& from);
  void MergeFrom(const JointTorques& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(JointTorques* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // repeated .salamander.msgs.JointTorque torque = 2;
  int torque_size() const;
  void clear_torque();
  static const int kTorqueFieldNumber = 2;
  const ::salamander::msgs::JointTorque& torque(int index) const;
  ::salamander::msgs::JointTorque* mutable_torque(int index);
  ::salamander::msgs::JointTorque* add_torque();
  ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointTorque >*
      mutable_torque();
  const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointTorque >&
      torque() const;

  // @@protoc_insertion_point(class_scope:salamander.msgs.JointTorques)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointTorque > torque_;
  friend void  protobuf_AddDesc_salamander_5fcontrol_2eproto();
  friend void protobuf_AssignDesc_salamander_5fcontrol_2eproto();
  friend void protobuf_ShutdownFile_salamander_5fcontrol_2eproto();

  void InitAsDefaultInstance();
  static JointTorques* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SalamanderControl

// repeated .salamander.msgs.JointCommands cmds = 1;
inline int SalamanderControl::cmds_size() const {
  return cmds_.size();
}
inline void SalamanderControl::clear_cmds() {
  cmds_.Clear();
}
inline const ::salamander::msgs::JointCommands& SalamanderControl::cmds(int index) const {
  // @@protoc_insertion_point(field_get:salamander.msgs.SalamanderControl.cmds)
  return cmds_.Get(index);
}
inline ::salamander::msgs::JointCommands* SalamanderControl::mutable_cmds(int index) {
  // @@protoc_insertion_point(field_mutable:salamander.msgs.SalamanderControl.cmds)
  return cmds_.Mutable(index);
}
inline ::salamander::msgs::JointCommands* SalamanderControl::add_cmds() {
  // @@protoc_insertion_point(field_add:salamander.msgs.SalamanderControl.cmds)
  return cmds_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointCommands >*
SalamanderControl::mutable_cmds() {
  // @@protoc_insertion_point(field_mutable_list:salamander.msgs.SalamanderControl.cmds)
  return &cmds_;
}
inline const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointCommands >&
SalamanderControl::cmds() const {
  // @@protoc_insertion_point(field_list:salamander.msgs.SalamanderControl.cmds)
  return cmds_;
}

// repeated .salamander.msgs.JointTorques torques = 2;
inline int SalamanderControl::torques_size() const {
  return torques_.size();
}
inline void SalamanderControl::clear_torques() {
  torques_.Clear();
}
inline const ::salamander::msgs::JointTorques& SalamanderControl::torques(int index) const {
  // @@protoc_insertion_point(field_get:salamander.msgs.SalamanderControl.torques)
  return torques_.Get(index);
}
inline ::salamander::msgs::JointTorques* SalamanderControl::mutable_torques(int index) {
  // @@protoc_insertion_point(field_mutable:salamander.msgs.SalamanderControl.torques)
  return torques_.Mutable(index);
}
inline ::salamander::msgs::JointTorques* SalamanderControl::add_torques() {
  // @@protoc_insertion_point(field_add:salamander.msgs.SalamanderControl.torques)
  return torques_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointTorques >*
SalamanderControl::mutable_torques() {
  // @@protoc_insertion_point(field_mutable_list:salamander.msgs.SalamanderControl.torques)
  return &torques_;
}
inline const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointTorques >&
SalamanderControl::torques() const {
  // @@protoc_insertion_point(field_list:salamander.msgs.SalamanderControl.torques)
  return torques_;
}

// optional .salamander.msgs.ControlAnalysis analysis = 3;
inline bool SalamanderControl::has_analysis() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SalamanderControl::set_has_analysis() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SalamanderControl::clear_has_analysis() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SalamanderControl::clear_analysis() {
  if (analysis_ != NULL) analysis_->::salamander::msgs::ControlAnalysis::Clear();
  clear_has_analysis();
}
inline const ::salamander::msgs::ControlAnalysis& SalamanderControl::analysis() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.SalamanderControl.analysis)
  return analysis_ != NULL ? *analysis_ : *default_instance_->analysis_;
}
inline ::salamander::msgs::ControlAnalysis* SalamanderControl::mutable_analysis() {
  set_has_analysis();
  if (analysis_ == NULL) {
    analysis_ = new ::salamander::msgs::ControlAnalysis;
  }
  // @@protoc_insertion_point(field_mutable:salamander.msgs.SalamanderControl.analysis)
  return analysis_;
}
inline ::salamander::msgs::ControlAnalysis* SalamanderControl::release_analysis() {
  // @@protoc_insertion_point(field_release:salamander.msgs.SalamanderControl.analysis)
  clear_has_analysis();
  ::salamander::msgs::ControlAnalysis* temp = analysis_;
  analysis_ = NULL;
  return temp;
}
inline void SalamanderControl::set_allocated_analysis(::salamander::msgs::ControlAnalysis* analysis) {
  delete analysis_;
  analysis_ = analysis;
  if (analysis) {
    set_has_analysis();
  } else {
    clear_has_analysis();
  }
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.SalamanderControl.analysis)
}

// -------------------------------------------------------------------

// ControlAnalysis

// repeated .salamander.msgs.JointConsumption joints_consumption = 1;
inline int ControlAnalysis::joints_consumption_size() const {
  return joints_consumption_.size();
}
inline void ControlAnalysis::clear_joints_consumption() {
  joints_consumption_.Clear();
}
inline const ::salamander::msgs::JointConsumption& ControlAnalysis::joints_consumption(int index) const {
  // @@protoc_insertion_point(field_get:salamander.msgs.ControlAnalysis.joints_consumption)
  return joints_consumption_.Get(index);
}
inline ::salamander::msgs::JointConsumption* ControlAnalysis::mutable_joints_consumption(int index) {
  // @@protoc_insertion_point(field_mutable:salamander.msgs.ControlAnalysis.joints_consumption)
  return joints_consumption_.Mutable(index);
}
inline ::salamander::msgs::JointConsumption* ControlAnalysis::add_joints_consumption() {
  // @@protoc_insertion_point(field_add:salamander.msgs.ControlAnalysis.joints_consumption)
  return joints_consumption_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointConsumption >*
ControlAnalysis::mutable_joints_consumption() {
  // @@protoc_insertion_point(field_mutable_list:salamander.msgs.ControlAnalysis.joints_consumption)
  return &joints_consumption_;
}
inline const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointConsumption >&
ControlAnalysis::joints_consumption() const {
  // @@protoc_insertion_point(field_list:salamander.msgs.ControlAnalysis.joints_consumption)
  return joints_consumption_;
}

// -------------------------------------------------------------------

// JointConsumption

// required string name = 1;
inline bool JointConsumption::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JointConsumption::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JointConsumption::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JointConsumption::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& JointConsumption::name() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointConsumption.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JointConsumption::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:salamander.msgs.JointConsumption.name)
}
inline void JointConsumption::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:salamander.msgs.JointConsumption.name)
}
inline void JointConsumption::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:salamander.msgs.JointConsumption.name)
}
inline ::std::string* JointConsumption::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointConsumption.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JointConsumption::release_name() {
  // @@protoc_insertion_point(field_release:salamander.msgs.JointConsumption.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JointConsumption::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.JointConsumption.name)
}

// required double consumption = 2;
inline bool JointConsumption::has_consumption() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void JointConsumption::set_has_consumption() {
  _has_bits_[0] |= 0x00000002u;
}
inline void JointConsumption::clear_has_consumption() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void JointConsumption::clear_consumption() {
  consumption_ = 0;
  clear_has_consumption();
}
inline double JointConsumption::consumption() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointConsumption.consumption)
  return consumption_;
}
inline void JointConsumption::set_consumption(double value) {
  set_has_consumption();
  consumption_ = value;
  // @@protoc_insertion_point(field_set:salamander.msgs.JointConsumption.consumption)
}

// -------------------------------------------------------------------

// JointCommands

// required string name = 1;
inline bool JointCommands::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JointCommands::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JointCommands::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JointCommands::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& JointCommands::name() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointCommands.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JointCommands::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:salamander.msgs.JointCommands.name)
}
inline void JointCommands::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:salamander.msgs.JointCommands.name)
}
inline void JointCommands::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:salamander.msgs.JointCommands.name)
}
inline ::std::string* JointCommands::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointCommands.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JointCommands::release_name() {
  // @@protoc_insertion_point(field_release:salamander.msgs.JointCommands.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JointCommands::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.JointCommands.name)
}

// repeated .salamander.msgs.JointState commands = 2;
inline int JointCommands::commands_size() const {
  return commands_.size();
}
inline void JointCommands::clear_commands() {
  commands_.Clear();
}
inline const ::salamander::msgs::JointState& JointCommands::commands(int index) const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointCommands.commands)
  return commands_.Get(index);
}
inline ::salamander::msgs::JointState* JointCommands::mutable_commands(int index) {
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointCommands.commands)
  return commands_.Mutable(index);
}
inline ::salamander::msgs::JointState* JointCommands::add_commands() {
  // @@protoc_insertion_point(field_add:salamander.msgs.JointCommands.commands)
  return commands_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointState >*
JointCommands::mutable_commands() {
  // @@protoc_insertion_point(field_mutable_list:salamander.msgs.JointCommands.commands)
  return &commands_;
}
inline const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointState >&
JointCommands::commands() const {
  // @@protoc_insertion_point(field_list:salamander.msgs.JointCommands.commands)
  return commands_;
}

// -------------------------------------------------------------------

// JointTorques

// required string name = 1;
inline bool JointTorques::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JointTorques::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JointTorques::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JointTorques::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& JointTorques::name() const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointTorques.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JointTorques::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:salamander.msgs.JointTorques.name)
}
inline void JointTorques::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:salamander.msgs.JointTorques.name)
}
inline void JointTorques::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:salamander.msgs.JointTorques.name)
}
inline ::std::string* JointTorques::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointTorques.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JointTorques::release_name() {
  // @@protoc_insertion_point(field_release:salamander.msgs.JointTorques.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JointTorques::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:salamander.msgs.JointTorques.name)
}

// repeated .salamander.msgs.JointTorque torque = 2;
inline int JointTorques::torque_size() const {
  return torque_.size();
}
inline void JointTorques::clear_torque() {
  torque_.Clear();
}
inline const ::salamander::msgs::JointTorque& JointTorques::torque(int index) const {
  // @@protoc_insertion_point(field_get:salamander.msgs.JointTorques.torque)
  return torque_.Get(index);
}
inline ::salamander::msgs::JointTorque* JointTorques::mutable_torque(int index) {
  // @@protoc_insertion_point(field_mutable:salamander.msgs.JointTorques.torque)
  return torque_.Mutable(index);
}
inline ::salamander::msgs::JointTorque* JointTorques::add_torque() {
  // @@protoc_insertion_point(field_add:salamander.msgs.JointTorques.torque)
  return torque_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointTorque >*
JointTorques::mutable_torque() {
  // @@protoc_insertion_point(field_mutable_list:salamander.msgs.JointTorques.torque)
  return &torque_;
}
inline const ::google::protobuf::RepeatedPtrField< ::salamander::msgs::JointTorque >&
JointTorques::torque() const {
  // @@protoc_insertion_point(field_list:salamander.msgs.JointTorques.torque)
  return torque_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace salamander

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_salamander_5fcontrol_2eproto__INCLUDED
