name: Build and Publish to PyPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - run: pip install cibuildwheel
      - run: cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v5
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pip install build
      - run: python -m build --sdist
      - uses: actions/upload-artifact@v5
        with:
          name: sdist
          path: dist/*.tar.gz

  publish_to_pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    needs: [bpuild_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    environment:
      name: pypi
      url: https://pypi.org/p/farms-core
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Download all the dists
        uses: actions/download-artifact@v6
        with:
          path: dist/
          merge-multiple: true
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
